buttonmen-dev/buttonmen

deploy/database/schema.game.sql
deploy/database/updates/00367_chat_length.sql
src/api/ApiSpec.php
src/ui/js/Game.js

Fixes #367.
Requires database update 00367_chat_length.sql.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/576/

Increased max chat message length from 500 characters to 2000 characters

---

src/engine/BMDie.php
src/engine/BMGame.php
test/src/engine/BMDieTwinTest.php
test/src/engine/BMGameTest.php

When digging for a solution to #1550, I noticed that the code in BMGame->getJsonData() assumed that the first subdie of a twin swing die would be a swing die. This pull request fixes the code for the case where the first subdie is not a swing die.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/655/

Fixed handling of asymmetric twin swing/non-swing dice in BMGame->getJsonData()

---

src/engine/BMInterface.php
test/src/api/responderTest.php

Fixes #1540.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/656/ (if it passes)

Chat now displays correct number of log entries, even when invisible entries are present

---

src/engine/BMDieTwin.php
src/engine/BMGameAction.php
test/src/api/responderTest.php
test/src/engine/BMGameActionTest.php

Fixes #1593. Also addresses the action logging wording left over from comments on #1583.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/678/

Time and Space now triggers correctly for twin dice

---

src/ui/js/Forum.js

Fixes #1336.
I'm thinking that there should probably be a QUnit test for this, but I don't yet know how to construct one.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/745/ (if it passes)

Added logic to disable "Mark thread as read" button when there is text in the reply box

---

test/src/api/responderTest.php

I noticed some bitrot between the live implementation of skill interaction descriptions, and the list responderTest uses to regression-test those interactions.  Here's a quick fix for responderTest to match the live implementation.
http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/411/ (assuming it passes)

Update responderTest list of skills to handle berserk/speed interaction

---

src/engine/BMSkill.php
src/engine/BMSkillMighty.php
src/engine/BMSkillMood.php
src/engine/BMSkillMorphing.php
src/engine/BMSkillNull.php
src/engine/BMSkillOrnery.php
src/engine/BMSkillRadioactive.php
src/engine/BMSkillValue.php
src/engine/BMSkillWeak.php
test/src/engine/BMGameTest.php
test/src/engine/BMSkillTest.php

Fixes #1645.
This addresses the interactions between boom and the following skills: 
- morphing
- null
- radioactive
- value
- mighty
- weak
- mood
- mad
- ornery
This will need quite a bit of testing by the testers, I expect.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/762/

Boom attacks now do not trigger side-effects from other skills

---

test/src/api/responderTest.php

Fixes regression caused by addition of game 036 responder test after previous merge which added action log count to API output.
Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/414/ (assuming it passes)

Handle undetected merge conflict in new responder test

---

src/engine/BMSkillMighty.php
src/engine/BMSkillWeak.php
test/src/api/responderTest.php

Fixes #1679.
Tested on a manually altered database state, with a skill attack using a hk(4) and a Hk(12) to capture an opponent's die.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/817/ (if it passes)

Fixed weak and mighty so that they don't trigger when the die doesn't reroll

---

deploy/database/schema.game.sql
deploy/database/updates/01580_database_index_02.sql

Continues to address #1580.
Requires database update 01580_database_index_02.sql
Tested with Aug 2 backup of live site, logged in as irilyth (with a password manually copied across from my account). Load times drop from 5 seconds to 1 second.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/839/ (if it passes)

Sped up Overview page by adding indices to database table game_player_map

---

src/engine/BMBtnSkill.php
src/engine/BMGame.php
src/ui/js/Game.js
test/src/api/responderTest.php
test/src/ui/js/test_Game.js

Fixes #1200.
I have added the button skills before the die skills, but not otherwise discriminated them, because this was the easiest thing to implement.
Tested with Giant vs RandomBMMixed, Echo vs Temperance, and Washu vs Shadow Warriors.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/834/

Added button special information to game screens

---

src/ui/js/Env.js

Fixes #1683.
Tested on the game page. I'm not aware of other space handlers, but I might have missed some.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/844/

Actively swallow a space character when there is an explicit handler for it

---

deploy/database/schema.stats.sql
deploy/database/updates/01580_database_indices_03.sql
src/engine/BMInterface.php

Continues to address #1580.
So, this pull request doesn't lead to huge improvements in performance, but it does stop the select_full_join count from increasing on:
- viewing button information (buttons.html and buttons.html?...)
- loading the create game page (create_game.html)
I watched the select_full_join count on my MAMP stack using the following query:
SELECT * from information_schema.global_status where variable_name='select_full_join';
Then, I looked up the slow queries, which had been logged because I had a my.cnf with the following contents:
[mysqld]
log-slow-queries = /Users/james/slow.log
long_query_time = 20
log-queries-not-using-indexes
The button query was rewritten because MySQL views don't support indexing.
Requires database update 01580_database_indices_03.sql …

Optimised button query, and added more database indices

---

deploy/database/schema.player.sql
deploy/database/updates/00205_reject_game_02.sql
src/api/ApiResponder.php
src/api/ApiSpec.php
src/api/DummyApiResponder.php
src/engine/BMGame.php
src/engine/BMGameState.php
src/engine/BMInterface.php
src/engine/BMInterfacePlayer.php
src/ui/js/Api.js
src/ui/js/Game.js
src/ui/js/Overview.js
src/ui/js/UserPrefs.js
test/src/api/responderTest.php
test/src/engine/BMGameStateTest.php
test/src/engine/BMInterface000Test.php
test/src/engine/BMInterfaceTest.php
test/src/engine/BMInterfaceTestAbstract.php
test/src/ui/js/test_Api.js
test/src/ui/js/test_Overview.js

Fixes #205.
This pull request does the following:
- add a new section to the Overview page called "New games", showing games that have not yet been accepted
- adds a user preference to auto-accept games, default on
Currently, the game page is minimal for a not-yet-accepted game or for a rejected game.
Requires database update 00205_reject_game_02.sql
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/898/

Allow game rejection

---

src/ui/js/Game.js

Fixes bug #1245.
I verified the links to the button exist for auxiliary selection page, reserve dice selection page, and swing dice selection page.
Jenkins still running as I post this, but here's a sample Jenkins for now: 
http://jenkins.buttonweavers.com:8080/job/buttonmen-dwvanstone/1/

Adding links to buttons in some selection pages (such as auxiliary dice)

---

src/engine/BMInterface.php
test/src/api/responderTest.php

Fixes #1274.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/919/

Set an explicit API message when joining an open game

---

src/engine/BMSkillTimeAndSpace.php

Fixes #1729.
Tested with artificially altered die recipes in the database, using odd-valued b^ and k^ dice.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/913/

TimeAndSpace now doesn't trigger if the die doesn't reroll

---

deploy/database/updates/01771_pending_game_01_dev.sql
src/engine/BMGame.php
src/engine/BMInterface.php
test/src/api/responderTest.php

Fixes #1771. Fixes #1788.
The dev database requires update 01771_pending_game_01_dev.sql
Once we add an appropriate responder test to this, I'll run Jenkins.

Fixed pending game count when games have been cancelled

---

src/engine/BMSkillMood.php
test/src/api/responderTest.php

Fixes #1723.
Game 1857 on the dev site will need to be fixed manually once this pull request is accepted. The fix is simply to set the appropriate die value to a valid value, and then change the game status from BROKEN to ACTIVE.
Tested Jenniegirl vs Jenniegirl.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/912/

Stopped mood skill triggering after a trip attack

---

src/ui/js/Api.js
test/src/ui/js/test_Api.js

Starts to address part of #1763.
This is a pure refactor, and shouldn't change any behaviour.
The aim of this pull request is to unify the duplicated codebase for different game types. It will simplify the process of changing the format of the New Games data from unsplit to split, which will then be achieved by simply changing parserargs.isSplit to true.
All further pull requests addressing #1763 will then be able to focus almost exclusively on Overview.js.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/953/ (if it passes)

Refactored Api to ensure consistent handling of data of different game types

---

deploy/vagrant/modules/buttonmen/templates/backup_database.erb

* Partially addresses problem that the backup disks on prod and (to a lesser extent) dev keep running out of space
* No jenkins because there are no changes to code that jenkins is aware of
* Tested manually on virtualbox with the dev database loaded:
```bash
sandbox,[~],13:32(0)$ ls -lart /srv/backup/
total 8
drwxr-xr-x 3 root root 4096 Nov 30 13:15 ../
drwxr-x--- 2 root adm  4096 Nov 30 13:32 ./
sandbox,[~],13:32(0)$ time sudo /usr/local/bin/backup_buttonmen_database
real    0m19.952s
user    0m18.453s
sys     0m1.084s
sandbox,[~],13:33(0)$ ls -lart /srv/backup/
total 2068
drwxr-xr-x 3 root root    4096 Nov 30 13:15 ../
drwxr-x--- 2 root adm     4096 Nov 30 13:32 ./
-rw-r--r-- 1 root root 2106650 Nov 30 13:33 buttonmen.20151130.sql.bz2
sandbox,[~],13:33(0)$ bzcat …
```

Run bzip2 on backups while storing them

---

src/engine/BMInterface.php
src/ui/js/Game.js
test/src/ui/js/test_Game.js

Continues to address part of #1731. Fixes #1778. Fixes #1779. Fixes #1766.
Known issues: Currently, the game page says unspecifically that the game was "rejected or cancelled". This will eventually be sorted out properly when #1816 is addressed.
The opponent's button table has been reversed, similar to the change in #1822.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/985/

Added game page for rejected/cancelled games

---

src/ui/js/Game.js

This pull request fixes the problem of the opponent's info not being visible on the game mat.
I am aware that there should be an appropriate unit test locking our expected behaviour into place, but I'd like to put this fix in first.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/997/

Fixed bug with displaying opponent info on the game mat

---

src/ui/js/Overview.js

Fixes #1850.
http://jenkins.buttonweavers.com:8080/job/buttonmen-dwvanstone/28/
I went with using the title "(N) Button Men Online" since that matches GitHub. 
An alternative would be to do what Google Mail does: "Overview (N) - Button Men Online." But I prefer having the title be as short as possible for this case.

Reformatted count of pending games in title.

---

src/ui/js/History.js
test/src/ui/js/test_History.js

Addresses part of #1840.
I am aware that the logic to detect new games is not really the best way, but until we explicitly add the ability to search for New Games in the history page (and perhaps add an extra game status type), the current implementation seems to be the easiest way to achieve the goal.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1011/

Changed W/L/T to –/–/– for rejected games on the history page

---

src/engine/BMInterface.php

Fixes #1517.
It is possible the change here has consequences (possibly good!) for chat editing at the end of game, or between rounds. Although this is currently not possible because we don't show the appropriate button on the UI, we *could*, if we wanted to.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1020/ (if it passes)

Changed criteria for chat editing to allow editing at start of round

---

src/api/DummyApiResponder.php
test/src/api/responderTest.php
test/src/ui/js/BMTestUtils.js
test/src/ui/js/test_Forum.js
test/src/ui/js/test_Game.js
test/src/ui/js/test_Newgame.js

Partially addresses #1858 but doesn't fix it entirely yet
* Generalize the framework for loading dummy data from files to support more API methods, and both successes and failures
* Migrate additional API methods to new test framework: createUser, createGame, countPendingGames, adjustFire, createForumThread, createForumPost
* Add a UI loadGameData failure test
Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/418/ (if it passes)

beginning of API test refactor and cleanup

---

src/ui/js/Forum.js

* Fixes #1888
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/421/

If Forum.showPage() is invoked with no usable state information, regenerate it from the URL

---

src/ui/js/Verify.js

What it says on the tin.  If you try to verify a user right now on dev or prod, you'll get a blank page.
Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/422/ (if it passes)

Fix regression which entirely broke user verification page

---

test/src/ui/js/test_Verify.js

This is a followup to #1907 with the goal of making jenkins pass.  My assertion is that the previous test was useless --- it was testing the exact function that let us show a blank page without noticing it.  IMO this will all come out in the wash in #1858 (which is what i was working on when i found this problem in the first place, natch), so debugging this interim test is not a good use of time, and we should just make Jenkins happy until we can fix it for real.
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/423/ (assuming it passes)

Strip out the Verify.showStatePage() test, since it was obviously useless

---

test/src/api/responderTest.php

No effect on existing tests, but these skill definitions are correct, and not having them sometimes causes false positives in regression tests i run with RandomAI.
Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/426/

Add a few missing skills and interactions to responderTest's hardcoded list

---

deploy/database/data.button.sql
deploy/database/updates/01927_mood_option_01.sql

Addresses part of #1927.
Requires database update 01927_mood_option_01.sql.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1054/

Disabled Connecticut so that mood option doesn't get misinterpreted

---

deploy/vagrant/modules/apache/templates/site_default.erb
src/api/ApiResponder.php

This will help us understand and detect the call failure problem being reported by players on the prod site (#1989), and detect problems in the future in which API calls are failing unexpectedly.
Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/431/ - if it passes
Additional testing done:
* Browsing to `http://localhost:8080/ui/game.html?game=1` (game 1 exists) yielded:
```
10.0.2.2 - - [13/May/2016:11:11:04 +0000] "POST /api/responder HTTP/1.1" 200 55 "http://localhost:8080/ui/game.html?game=1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:46.0) Gecko/20100101 Firefox/46.0" BMUser=- BMAPI=loadPlayerName BMStatus=ok
10.0.2.2 - - [13/May/2016:11:11:04 +0000] "POST /api/responder HTTP/1.1" 200 103 "http://localhost:8080/ui/game.html?game=1" "Mozilla/5.0 (Macintosh; …
```

Use apache to log whether API calls are successful within the BM engine

---

deploy/database/schema.game.sql
deploy/database/updates/01991_action_log.sql
deploy/database/updates/scripts/01991_migrate_end_draw_action_logs
deploy/database/updates/scripts/README
deploy/vagrant/modules/mysql/manifests/init.pp
src/engine/BMGame.php
src/engine/BMGameAction.php
src/engine/BMInterface.php
src/engine/BMInterfaceGame.php
src/engine/BMInterfaceGameAction.php
test/src/engine/BMGameActionTest.php
test/src/engine/BMInterfaceGameActionTest.php

* This is the proposed framework for #1991
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/434/
In this pull:
* Create BMInterfaceGameActionLog.php and move the handful of existing action_log database functions there
* Add generic logic to action_log load and save methods to use dedicated tables where they exist
* Migrate the `end_draw` action log entry's load/store methods to use such a dedicated table, `game_action_log_type_end_draw`
* Provide an idempotent utility to be run as part of the deployment which migrates all existing `end_draw` entries

Migrate action_log entries of type end_draw to new database structure

---

deploy/database/updates/scripts/01991_migrate_end_draw_action_logs

* Related to #1991 
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/436/ (should pass, i haven't changed anything Jenkins tracks)
Tested by loading databases from each of the dev and prod sites, and seeing that they both could still be migrated, and that early dev games containing draws still looked right.

Fix end_draw to work with grandfathered string entries from very early on the dev site

---

deploy/database/schema.game.sql
deploy/database/updates/01991_action_log.sql
deploy/database/updates/scripts/01991_migrate_end_draw_action_logs
src/engine/BMInterfaceGameAction.php

* Related to #1991 
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/439/
I apologise for all the bother --- i think it makes much more sense to do things this way, and the fact that it simplifies the database update (no modify to game_action_log needed), saves space while we're in transition, and makes it easier to handle the case where no auxiliary table is needed (just have a secondary function with the usual name which returns empty params, rather than hardcoding an exception), makes me confident that this change is the right thing.

Change the database format for end_draw to put the index in the secondary table

---

deploy/database/updates/scripts/02003_fix_all_twin_dice

* Fixes #2003 
* Not bothering with jenkins because there's nothing testable here
This script reports on three die cases and tries to fix one of them:
* die->value is set and die is not a swing die, but there are no twin flags - the script fixes this case by setting the twin flags to something reasonable
* die->value is set and die is a swing die, but there are no twin flags - the script does not fix this case, and it seems from experimentation like this case is somewhat self-repairing as the game progresses
* die->value is not set, and twin flags have sides, but no values - this could be a sign of a game that is already unloadable, or it could represent some other case, so the remedy is just to check by hand and see if the game is loadable
This script will not repair game 1806 on prod, …

Script to fix twin dice in live databases

---

deploy/vagrant/modules/apache/templates/monitor_apache_logs.erb

Goal here is just to make the apache log monitor a bit more usable - i've been finding that i fall pretty far behind on the mail it sends, which means i'm not using it as a straightforward way to detect internal errors in real-time.

Exclude common ignorable errors from apache log monitor so it is usable

---

deploy/database/schema.game.sql
deploy/database/updates/01991_action_log_turndown_focus.sql
deploy/database/updates/scripts/01991_migrate_turndown_focus_action_logs
src/engine/BMGame.php
src/engine/BMGameAction.php
src/engine/BMInterfaceGameAction.php
test/src/engine/BMGameActionTest.php

* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/449/ (if it passes)
Note that this is the first example of a case in which there might be more than one secondary table entry per primary log entry.  IMO it's pretty clean, but obviously i'll be doing a bunch more of this when i get to stuff like specify_dice and attack.  Worth noting is that i named the secondary table `...turndown_focus_die` rather than `...turndown_focus` as a marker that it's a per-turndown-focus-entry-die table rather than a per-turndown-focus-entry table (and when i get to specify_dice and attack there may be more than one secondary table, each storing a different type of secondary data).
Also worth noting is that the savings here are pretty big per-entry (though of …

Move turndown_focus action_log secondary information to dedicated tables

---

src/engine/BMGame.php
test/src/engine/BMGameTest.php

* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/450/
Obviously, there's no reason at all to merge this until after the merge freeze - i just noticed the issue and figured i'd submit the fix while i was thinking about it.

Strip a test hook out of reroll_chance because we can just use the RNG override

---

deploy/database/updates/scripts/01991_migrate_init_decline_action_logs
src/engine/BMGame.php
src/engine/BMInterfaceGameAction.php
test/src/engine/BMGameActionTest.php

* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/454/ (if it passes)
This one should be pretty boring - unless i mucked up the merge and it fails tests, i doubt there's anything to see here.

Remove extraneous parameter from init_decline action log messages

---

test/src/api/responderTest.php
test/src/ui/js/BMTestUtils.js
test/src/ui/js/test_Game.js

* Related to #822 
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/460/
This doesn't refactor anything yet --- it just significantly fleshes out the unit tests of `Game.gamePlayerDice()`, in particular:
* Using a test method i wrote some time ago but haven't used much yet, fully regression-test the set of DOM properties for some of the dice
* Add testing for dizzy dice (this is just a minor variant on the existing warrior test, of course, but it helps test coverage)
* Add testing for the case in which `Game.activity.dieSelectStatus` is set before loading the dice, to verify that dice will have the correct classes to be outlined in red in that case

add unit tests for UI gamePlayerDice() method

---

src/ui/js/Game.js
test/src/ui/js/test_Game.js

* Related to #822 and #2047, a suggested replacement refactor for #1981
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/461/ (if it passes)
This splits the monolith `Game.gamePlayerDice()` function into a number of distinct functions, which ideally has the effect of splitting things cleanly into functions which gather information and functions which lay out particular elements, and making operation consistent across active and captured dice.
The refactor *should* be a total noop --- the only difference is that it reorders class attributes in a couple of cases, but it should not add or remove attributes in any case, but only move code around.

refactor the Game.gamePlayerDice() function

---

deploy/database/schema.game.sql
deploy/database/updates/00464_chat_privacy.sql
src/engine/BMInterface.php
src/engine/BMInterfaceGameChat.php
src/engine/BMPlayer.php
src/ui/js/Game.js
test/src/api/responderTest.php

* Partially addresses #464 
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/472/
This pull adds a private chat flag to the game_player_map database table, and implements the concept that, if that flag is set for either player in a game, non-players cannot load the chat for that game, but instead load, as part of the normal chat stream, a message saying that game chat is private.
This pull does not provide support for setting the private chat flag, so it does not make any chat privacy functionality available to players.
This pull changes the behavior of continuation chat in all games per https://github.com/buttonmen-dev/buttonmen/issues/464#issuecomment-231558844 option 4 --- non-players no longer see chat from previous games when they load a game which is a …

Implement the concept of private chat in the backend and chat-loading layers

---

test/src/api/responderTest.php

* Convenience pull to address spurious errors in my RandomAI regression testing
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/474/ (if it passes)

Add missing new button specials to responderTest's skill list

---

src/ui/js/Overview.js

* Mitigates the effect of #2081 
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/475/ (if it passes)
This is just the fix i already manually applied to the dev and prod sites.  Obviously the backend mismatch is what we need to fix, but regardless it's not bad for the UI to be resilient if the backend gives it bad data.

Overview.addDescCol() should not blow up if description is null

---

src/ui/gui.css

Partially addresses #2070.
This changes the font size from 24 px to 20 px, and adds a Firefox-specific CSS rule that has different vertical spacing, to account for the unusual amount of padding at the bottom of the die value span that Firefox adds for some odd reason.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1199/ (if it passes)

Made die value number smaller, added specific vertical spacing for Firefox

---

src/engine/BMInterface.php
test/src/api/responderTest.php

Fixes #2094.
This is the minimal quick fix that resolves the symptoms but does it in a way that leaves the API response inappropriate. #2097 is probably a better solution, but I'll leave this one up in case it's simpler.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1220/

Die background is now correctly always specified by the viewing player's preferences

---

src/engine/BMAttackDefault.php

Proposed fix for #1721.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1232/ (if it passes)

testing: Fixed default attack when fire overshooting is off

---

deploy/vagrant/modules/jenkins/templates/buttonmen_config.xml.erb

Technically, we don't config-manage config.xml for each individual jenkins project, so i manually made this change to `/srv/jenkins-jobs/buttonmen-cgolubi1/config.xml`, and then reran jenkins (not on this branch, but it doesn't matter) - http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/487/console - where you can see it ran jshint at the beginning instead of the end.
If this is approved, i'll deploy the template change in the usual way, and reconfigure the existing jobs.

In jenkins, run grunt scripts before processing build.xml

---

tools/api-client/python/lib/random_ai.py

Another RandomAI-only fix, which should address a stacktrace exception i found on the site that records new replay games today.
Sorry for the sloppiness.

Actually include SWING_RANGES variable used by trip turbo code

---

test/src/api/responderTest.php

* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/489/ (if it passes)
This is a first step towards addressing a problem i'm having in regression-testing Rush, namely that all the RandomBM* replay tests fail because the random numbers have changed.  I'll still have to do the work of making RandomAI figure out which die rolls are skill selection and abstract those out when storing games for replay, but if we agree on the approach, i can then do that.
Also this change should be helpful to Shadowshade in adding new non-excluded skills, because it'll mean only one change to responderTest is needed to get all the RandomBM* tests caught up with the new values.

Abstract the die rolls for the RandomBM skills used by respondertest

---

src/engine/BMGame.php
src/engine/BMInterface.php
src/engine/BMInterfaceGame.php
test/src/api/responderTest.php
test/src/engine/BMInterfaceGameTest.php
test/src/engine/BMInterfacePlayerTest.php
test/src/engine/BMInterfaceTest.php
test/src/engine/BMInterfaceTestAbstract.php

Starts to address #1784, but should leave user-visible behaviour untouched.
Note that it should now be possible to create third-party games by directly addressing the responder, e.g., via the Python client.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1219/ (if it passes)

Backend changes to enable third party game creation

---

src/api/ApiResponder.php
src/api/ApiSpec.php
src/api/DummyApiResponder.php
src/engine/BMInterface.php
src/engine/BMInterfaceGameChat.php
test/src/api/responderTest.php
test/tools/api-client/python/lib/test_bmapi.py

* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/491/ (if it passes)
* Partially addresses #464 
This pull builds on the backend chat privacy work i did last year in #2065 by implementing an API method, `setChatVisibility`, which can be used to turn chat privacy on and off.
This change does not yet make chat visibility usable by UI players, but it gives us the last API piece we need for that.  The next PR will be the UI piece to display chat privacy information in a friendly way, and to provide a way to call this new API method.

Implement setChatVisibility API method

---

tools/api-client/python/lib/random_ai.py

Without this change, `replay_loop` blows up on `prep_replay_games`.  I should do replay-testing on my own pulls which change the API; that was my bad.
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/496/ (if it passes)

Make randomAI able to do replay testing now that we have isChatPrivate in the API response

---

deploy/vagrant/modules/apache/templates/monitor_apache_logs.erb

* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/503/ (if it passes)
Tested on virtualbox that i didn't break the file syntactically:
```bash
sandbox,[~],00:18(0)$ sudo /usr/local/sbin/monitor_apache_logs
[Sun Aug 20 00:16:36 2017] [notice] caught SIGTERM, shutting down
[Sun Aug 20 00:16:46 2017] [notice] caught SIGTERM, shutting down
sandbox,[~],00:18(0)$ sudo /usr/local/sbin/monitor_apache_logs
sandbox,[~],00:20(1)$ 
``

Ignore frequent doorknob-rattling rejection that's making error log mail hard to scan

---

tools/api-client/python/lib/random_ai.py

* Needed for functionality testing of #2085 
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/506/ (if it passes)
Testing done: with this loaded, archived replay games started using:
```
./test_log_games 100 random=True
```
and that successfully invokes create_game with `__random` and replay tests succeed.

RandomAI's button selector should support asking the server for a random button

---

src/engine/BMGame.php
src/engine/BMInterface.php
src/ui/js/Api.js
src/ui/js/Game.js
test/src/api/responderTest.php
test/tools/api-client/python/lib/test_bmapi.py

Addresses part of #1784.
Currently, what I've done here is add the creator info to the response sent from the backend, then if the creator is not one of the two players in the game, I've shown the creator on the game screen. There's no change to the Overview screen yet.
If we want any changes to the Overview screen, I'd suggest that we do that in a separate pull request.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1357/ (if it passes)

Added third-party creator to game page

---

src/ui/active_players.html
src/ui/buttons.html
src/ui/create_game.html
src/ui/create_user.html
src/ui/forum.html
src/ui/game.html
src/ui/history.html
src/ui/index.html
src/ui/js/Loader.js
src/ui/open_games.html
src/ui/prefs.html
src/ui/profile.html
src/ui/verify.html
test/src/ui/js/test_Loader.js

* Fixes #2260
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/514/
I didn't do significant testing that this fixes the particular problem, because that's hard to setup.  But i tested that the pages still seem to load, which is the important part.  Given that it doesn't break page loads, it *should* fix the problem (given that the version cookie business helped for other JS files), and the implementation is such that it shouldn't have any impact on your plan for keeping things working on your windows stack - the sed stuff didn't change at all, so your existing set of symlinks should still be just fine.

Pass the version cookie to Loader.js and use it when loading default BM modules

---

tools/api-client/python/lib/random_ai.py

* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/515/ (if it passes)
I went to check in on my long-running replay site and found it had stopped its loop due to this bug, which it encountered in CestWest vs Wyoming.  The problem was immediately reproducible.  With this fix, it successfully played over 20 CestWest vs Wyoming games without blocking.

Fix bug in (hackish) handling of trip turbo range in RandomAI

---

tools/api-client/python/lib/random_ai.py

* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/516/ (if it passes)
Shadowshade: sorry for the inconvenience.  It would be fair to ask how i can possibly accept so many pulls that break replay testing without noticing.  I think i'm just not good at remembering that API changes that obviously aren't game logic regressions, nevertheless impact replay testing.  Anyway, this is all in service of getting to the point where i can do replay testing for things in the queue that actually might impact game logic, so help me keep churning through these, and thanks in advance.

creatorDataArray is a key that will not change during replay

---

src/engine/BMInterfaceGame.php
test/src/api/responderTest.php

Fixes #2258.
There's no easy fix to the database to get these games running again with the correct logging.
I propose that we set the status of these games to BROKEN (status = 5), which will hide them from the Overview screen.
If that is considered to be too drastic, we could set the game_state in the 'game' table manually back to 40 (START_TURN), and toggle the is_awaiting_action values in the 'game_player_map' table for both players. That will get the games going, but the logging will be incorrect for the one broken attack.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1378/

Fixed bug with fire decline turndown and turbo

---

deploy/database/data.game.sql
deploy/database/updates/01839_new_in_progress_history_01.sql
src/api/ApiSpec.php
src/engine/BMInterface.php
src/engine/BMInterfaceHistory.php
src/ui/js/Env.js
src/ui/js/History.js

Fixes #1839. Fixes #1840.
I've tested this with OPEN games (i.e., ones where the opponent is not specified), NEW games (i.e., not yet accepted by opponent), ACTIVE games, COMPLETED games, and CANCELLED games. They all show correctly, and filtering by type also seems to work.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1411/

Changes to allow History page to show new games

---

test/src/api/responderTest.php

This fixes a unit test regression that was caused by the acceptance of #2275 to fix #2217.
This needs to be accepted as a matter of priority, because the master branch currently doesn't pass Jenkins.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1431/

Fixed unit test regression for turbo log message

---

src/engine/BMBtnSkillGordo.php
src/engine/BMBtnSkillGuillermo.php
src/engine/BMBtnSkillUniqueSwing.php
src/engine/BMGame.php
src/engine/BMInterfaceGame.php
test/src/engine/BMBtnSkillGiantTest.php
test/src/engine/BMBtnSkillGordoTest.php
test/src/engine/BMBtnSkillGuillermoTest.php
test/src/engine/BMBtnSkillUniqueSwingTest.php
test/src/engine/BMGameTest.php

Fixes #265.
This pull request enables Gordo and Guillermo. It enforces the uniqueness of all die sizes for Gordo, and just swing values for Guillermo. It also stops players from accepting an aux die for Gordo that is a swing die with a type already in Gordo's recipe.
I've tested this with Gordo vs Guillermo, Gordo vs King Arthur, and Gordo vs Lancelot.
In addition, I've removed an unused argument in Giant's button special, which I noticed when I was using it as a template for these button specials.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1398/ (if it passes)

Added functionality for Gordo and Guillermo

---

src/engine/BMAttackSkill.php

Fixes #2304.
I've tested this with wtrollkin vs eon, replicated the situation, and then used a t(1) to trip a s%(S=20)! die 40 times in a row, which generated 40 t(0) dice. With the fix, the site did not lose responsiveness.
Naturally, this doesn't address the issue of whether it's too silly to be actually generating 40 t(0) dice, but that's something for further discussion elsewhere.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1441/

Strip excess zeros when looking for potential skill attacks

---

src/engine/BMSkillMad.php
src/engine/BMSkillMood.php
src/engine/BMSkillRadioactive.php
src/engine/BMSkillTimeAndSpace.php
src/engine/BMSkillTurbo.php
test/src/api/responderTest.php

Fixes #1794 better.
I've altered the interaction descriptions so that they now more correctly reflect the loss of various skills when decaying due to Radioactive. I've also added Mad Swing explicitly to the description of Radioactive, and added the Mad Swing interaction descriptions.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1450/ (if it passes)

Corrected radioactive interaction descriptions

---

src/ui/js/Game.js

Fixes #1716.
I've tested this with wranklepig vs wranklepig.
As part of the logic, I've included what should work with a button with twin stinger and a fire die, but I haven't been able to test this because there is no such button at the moment.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1443/ (if it passes)

Added logic to consider stinger dice in fire attack guidance

---

src/ui/gui.css
src/ui/js/Env.js
src/ui/js/Forum.js

Fixes #1905.
The current solution only allows linking to forum threads, not posts. To allow links to posts, the simplest way would be to not escape the parameter, but I'm uncertain whether we should be allowing unescaped parameters here.
Edit: the new solution allows linking to forum posts too.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1395/ (if it passes)

Added forum markup to link to other forum threads

---

deploy/vagrant/modules/php/manifests/init.pp

* Fixes #2362 
* Testing: applied the change when standing up a replay site and verified that puppet succeeded.

Don't verify SSL cert when downloading phpunit

---

.circleci/config.yml
deploy/circleci/verify_dummy_responder_files.sh

* Partially addresses #2342 
* I can't prove this works or that i've diagnosed the problem correctly --- my test CircleCI run passed on the first try, and we know we're getting spurious QUnit failures pretty often in CircleCI (i'd say at least 1/5 of the time?), so if we merge this and don't see more spurious failures, or if we merge this and ever see it need to sleep once before continuing, we should feel very confident in it.  And if we merge this and do see another spurious failure, we can go back to the drawing board.

Add a CircleCI step which tries to verify that the dummy API files have landed before running QUnit

---

tools/api-client/python/replay_loop

I sometimes see replay_loop commands error out with this exception:
```
Testing fecc05e96963fd94775e7e0e16bdc53dff6608e3.games.20180515.034014.tar.bz2...
tar: This does not look like a tar archive
bzip2: Compressed file ends unexpectedly;
perhaps it is corrupted?  *Possible* reason follows.
bzip2: Inappropriate ioctl for device
Input file = (stdin), output file = (stdout)
It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.
You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
command failed: tar xf /srv/bmgames/chaos-test/archive/fecc05e96963fd94775e7e0e16bdc53dff6608e3.games.20180515.03401 …
```

replay_loop should retry tar command

---

src/ui/js/Newgame.js
test/src/ui/js/test_Newgame.js

Fixes #1796.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1444/ (if it passes)

Removed "Any button" option when filters are selected

---

deploy/database/schema.player.sql
deploy/database/updates/01167_php7_01.sql
src/api/ApiResponder.php
src/api/api_core.php
src/engine/BMInterfaceNewuser.php
src/engine/BMInterfacePlayer.php

Addresses the codebase part of #1167. Fixes #884.
The changes here fall into two categories:
1. Indirect expressions are handled differently in PHP 7.
See http://php.net/manual/en/migration70.incompatible.php for details.
2. New functions for password hashing and verification were added in PHP 5.5, and the use of a manual salt was deprecated in PHP 7.0.
See http://php.net/manual/en/function.password-hash.php for details.
I've added code here to convert short hashes (length 34) to long hashes (length 60) on successful login. I've also added a database update to increase the hash field sizes to 255, on the basis of advice from the PHP doc page for password_hash.
I've tested the following with my MAMP stack under PHP 7.1.13: logging in, logging out, creating a new user, and validating a new …

Added logic to migrate up to PHP 7

---

tools/api-client/python/replay_loop

Fixes this:
```
...
Prepping game for replay from: ./output/game00100.pck
Testing 3d32b0989a9e10028aa3797140d64bbc9ca1abdf.games.20180619.135321.tar.bz2...
tar: This does not look like a tar archive
bzip2: Compressed file ends unexpectedly;
perhaps it is corrupted?  *Possible* reason follows.
bzip2: Inappropriate ioctl for device
Input file = (stdin), output file = (stdout)
It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.
You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Traceback (most recent call last):
File "./replay_loop", line 172, in <module>
test_file(nextfile)
File …
```

Fix typo in error message causing retry not to work

---

deploy/vagrant/modules/php/manifests/init.pp

* Fixes download of phpunit.phar failing yet again
This isn't a great solution, but the version of phpunit.phar we're downloading is over a year old anyway, so we're not really missing updates, and i'd rather pick a workaround that keeps us moving for now and focus on upgrading php / ubuntu, than sink a lot of time into debugging why the handshake is unhappy.

Get phpunit from a version stashed on a local webserver to work around changes in phar.phpunit.de's SSL accessibility

---

deploy/database/schema.game.sql
deploy/database/updates/01991_action_log_determine_initiative.sql
deploy/database/updates/scripts/01991_migrate_choose_swing_action_logs
deploy/database/updates/scripts/01991_migrate_determine_initiative_action_logs
src/engine/BMGame.php
src/engine/BMGameAction.php
src/engine/BMInterfaceGameAction.php
test/src/engine/BMGameActionTest.php

* Also migrate very old "choose_swing" entries to "choose_die_values" in the database
A couple of relevant notes, if this passes:
* The "choose_swing" script is totally unrelated to everything else in the pull, and is a very simple modification of the choose_die_values script.  It only affects very old games, and should be a no-brainer and not distracting from the rest of the pull, but if you find that it is, complain, and i'll remove it.
* "determine_initiative" is the first action log entry type that iterates over dice, so there's a model for that here, where i retain only the information about each die which is actually used to construct the action log entry.  Obviously in the future when i'm creating "attack" type action log entries, what i retain will be …

Migrate action log entries of type determine_initiative to dedicated tables

---

tools/api-client/python/replay_single_game

I realised this would make my life easier if i wanted to get serious about actually testing around expected API changes, e.g. my comment in #2384.  Here's an example of what it looks like:
```
ip-172-31-34-85,[~],13:06(0)$ ./replay_single_game be49150ca786d69a093216fc2aae7666107afd5c.games.20180819.091048.tar.bz2 00034
<?php
require_once 'responderTestFramework.php';
class responder99Test extends responderTestFramework {
Updating and prepping game for replay from: ./output/game00034.pck
About to execute: sudo -u ubuntu sh -c "php /etc/php5/deploy-includes/phpunit.phar --bootstrap /usr/local/etc/buttonmen_phpunit.php --group fulltest_deps /buttonmen/test/src/api/ 2>&1"
PHPUnit 4.8.36 by Sebastian Bergmann and contributors.
.F
Time: 1.22 seconds, Memory: 40.75MB
There was 1 failure:
1) …
```

Utility to replay a single game from a recorded archive

---

src/ui/js/OpenGames.js

Fixes #1755.
The message that is displayed causes the open games table to shift downwards, which I think is undesirable. It's probably better to always reserve the space for the message, but I don't know how to do this. Suggestions are welcome.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1226/ (if it passes)

Display UI messages when joining an open game

---

.circleci/config.yml
deploy/circleci/manifests/init.pp
deploy/vagrant/Vagrantfile
deploy/vagrant/manifests/init.pp
deploy/vagrant/modules/apache/manifests/init.pp
deploy/vagrant/modules/apache/templates/site_default.erb
deploy/vagrant/modules/apt/manifests/init.pp
deploy/vagrant/modules/apt/templates/10periodic.erb
deploy/vagrant/modules/buttonmen/manifests/init.pp
deploy/vagrant/modules/buttonmen/templates/phpunit.php.erb
deploy/vagrant/modules/buttonmen/templates/run_buttonmen_tests.erb
deploy/vagrant/modules/javascript/manifests/init.pp
deploy/vagrant/modules/javascript/templates/install_phantomjs.erb
deploy/vagrant/modules/mysql/manifests/init.pp
deploy/vagrant/modules/mysql/templates/buttonmen.cnf.erb
deploy/vagrant/modules/php/manifests/init.pp
src/engine/BMInterfaceGame.php
test/src/engine/BMGameTest.php
test/src/engine/BMInterfaceGameTest.php
test/src/engine/BMInterfaceTest.php
tools/api-client/python/replay_loop
tools/api-client/python/replay_single_game
util/grunt/circleci-grunt.sh

* Fixes #2398
* Replaces #2412 and partially addresses the same issues as #2411 --- we'll bring those changes in after the upgrade

Upgrade buttonweavers site to Ubuntu Xenial

---

src/api/ApiResponder.php
src/api/ApiSpec.php
test/src/api/responder01Test.php
test/src/api/responder02Test.php
tools/api-client/python/replay_loop

* Fixes #2433
The `LOGF.flush()` is unrelated --- it's something i want to get my log updated faster, and have been too lazy to submit a separate pull for it.

Python client should sort keys when JSON-encoding them for API submission

---

.circleci/config.yml
deploy/vagrant/modules/php/manifests/init.pp

* Fixes #2444 (if it passes circleci)
I could probably safely migrate more of the PHP checking stuff from downloading phar files to apt-get, but i wanted to start with the thing which is actually broken to get a PR in today.

Get phploc from apt rather than downloading the phar

---

deploy/vagrant/modules/apache/templates/monitor_apache_logs.erb

This is to reverse some bitrot in the amount of noise e-mail i've been getting from buttonmen apache error logs, to make scanning them for real errors less time-consuming.
I tested the recipe on some live dev sites that have been spamming me, and verified that the greps work to remove the messages they're targeting.

Exclude some common unimportant error log messages

---

deploy/vagrant/manifests/init.pp
deploy/vagrant/modules/cloudwatch/manifests/init.pp
deploy/vagrant/modules/cloudwatch/templates/record_buttonmen_metrics.erb

This is a very simple implementation of site health metrics using cloudwatch:
* On non-AWS sites, this does nothing
* On AWS sites, it installs aws-cli (used to record metrics)
* Every five minutes, it:
* Uses logtail to find new entries in the apache access log
* Looks for entries which are POSTs to /api/responder
* Parses out from each entry what the API call was, and whether it succeeded
* Emits a metric whose value is the success (1 on success, 0 on failure), and whose dimensions are the instance ID (which effectively tells us what buttonmen site it is) and the API call in use (just in case this is interesting)
This should be enough to allow us to alarm on whether a site hasn't seen any traffic in awhile, and on whether call success rate is low, whatever proves useful to us.

On AWS instances, emit cloudwatch metric entries recording API call success

---

deploy/vagrant/modules/cloudwatch/manifests/init.pp
deploy/vagrant/modules/cloudwatch/templates/record_buttonmen_metrics.erb

When i pushed the changes to staging, i started getting these cron failure e-mails:
```
Traceback (most recent call last):
File "/usr/local/bin/record_buttonmen_cloudwatch_metrics", line 8, in <module>
REGION = sys.argv[2]
IndexError: list index out of range
```
on bmstaging:
```
$ facter ec2_placement_region
$ facter ec2_placement_availability_zone
us-east-1a
```
(vs on the dev site where i tested this code initially:
```
$ facter ec2_placement_region
us-east-1
$ facter ec2_placement_availability_zone
us-east-1c
```
So... fine.  Hand the AZ to the script and have the script chop it off.

use ec2_placement_availability_zone fact, because ec2_placement_region is not always available

---

deploy/vagrant/modules/cloudwatch/templates/record_buttonmen_metrics.erb

I just made this change by hand on staging and prod because to do otherwise would be ridiculous, but here it is in the codebase.

Remove debugging statements from cron jobs

---

deploy/vagrant/Vagrantfile
deploy/vagrant/modules/cloudwatch/manifests/init.pp
deploy/vagrant/modules/cloudwatch/templates/record_buttonmen_metrics.erb

* Use boto instead of awscli so we're not spawning a process per metric
* Emit a sum per API call type, rather than one metric per individual call
* Emit a total metric and a failure metric, so we can look at load and at failures
* Emit a total, which will be zero if there are no calls in that interval
* Timeout the entire cron job if it's not done in 15 seconds
* Actually set the IAM role for new AWS instances (so dev/replay instances can emit cloudwatch metrics at all)
This partially addresses #2536 and is the same change as #2605 (so you can see the graphs there for what the behavior looks like), just in a clean branch for git merge laziness reasons.

Make bmsite cloudwatch metrics more user-friendly for production use

---

src/engine/BMUtilityXCYIterator.php

Fixes #2591.
I *think* I understand why this hasn't caused any trouble, but I'm not entirely sure. My thinking is the following:
The bad code is
if (count(array > 0) && ...) {...}
and the fixed code is
if ((count(array) > 0) && ...) {...}
If you think about it,
array > 0
produces an array of logicals, so
count(array > 0)
is just the same as
count(array)
and since this is in an 'if' statement, it gets converted to a logical, meaning that it's equivalent to
count(array) > 0
However, if I could have this wrong.
Anyway, I'll let the unit tests have the last word.

Fixed PHP warning caused by incorrect bracketing

---

deploy/amp/phpunit_bootstrap.php
deploy/circleci/phpunit_bootstrap.php
src/engine/BMAttack.php
src/engine/BMButton.php
src/engine/BMDie.php
src/engine/BMDieTwin.php
src/engine/BMEmail.php
src/engine/BMGame.php
src/engine/BMGameAction.php
src/engine/BMInterface.php
src/engine/BMInterfaceGame.php
src/engine/BMInterfaceNewuser.php
src/engine/BMPlayer.php
src/engine/BMSkillMaximum.php
src/engine/BMSkillMighty.php
src/engine/BMSkillTimeAndSpace.php
src/engine/BMSkillTrip.php
src/engine/BMSkillTurbo.php
src/engine/BMSkillWeak.php
src/engine/BMUtilityHitTable.php
test/src/engine/BMButtonTest.php
test/src/engine/BMDieOptionTest.php
test/src/engine/BMGameTest.php
test/src/engine/BMInterfaceGameTest.php
test/src/engine/BMInterfaceTest.php
test/src/engine/BMSkillBerserkTest.php
test/src/engine/BMSkillRadioactiveTest.php
test/src/engine/BMSkillRageTest.php
test/src/engine/BMSkillTimeAndSpaceTest.php

Fixes #1167.
So, this pull request is intended to fix the calls to isset() and empty() in the code and test code that were broken by the upgrade from PHP 5.2 to PHP 7.0.
We already know from Chaos's replay testing that these changes break something with Dead Guy, so I'll mark this as incomplete until we have a responder test for that problem and the problem has been fixed.

Fix isset() and empty() calls broken by PHP version upgrade

---

tools/api-client/python/lib/bmapi.py

I think the branch name says it all.
Now that i've seen how easy it is to cast numbers at the API layer as part of addressing #712 i'm going to do it, but this PR addresses why my testing of #2389 keeps falling over.

Fix truthiness check on auxiliary and reserve adds to work with buttons whose first die is +/r

---

src/engine/BMDie.php
src/engine/BMFlagHasJustBeenMoody.php
src/engine/BMSkillMood.php
test/src/api/responder01Test.php
test/src/api/responder02Test.php
test/src/api/responder03Test.php
test/src/engine/BMFlagHasJustBeenMoodyTest.php

This is the first component extracted from pull request #1675. It simply adds the flag HasJustBeenMoody, which will be used for correctly logging mood die size changes.

Added flag HasJustBeenMoody to mood dice that have just attacked

---

deploy/circleci/audit_php_files.php
src/api/ApiResponder.php
src/api/ApiSpec.php

So this isn't all the work that's needed for #712 but i was wondering whether it would be easier to put up smaller PRs that touched smaller pieces of the codebase.  This particular piece touches only `src/api`, and does:
* Move all casts of elements in `$args` to numbers into `ApiSpec.php` (and in particular into one generic method within `ApiSpec.php` that casts all API arguments of type `number`)
* Make it so the only `(int)` casts remaining within `ApiResponder.php` are casts of elements of `$_SESSION`
* Add a regression test so that as we start stripping `(int)` casts from the codebase, we can't backslide
Future pieces will traverse `src/engine` and make that so that all `(int)` casts occur when pulling things from the database.

Cast all number arguments to int in ApiSpec, rather than one-off in ApiResponder

---

deploy/circleci/audit_php_files.php
src/api/ApiResponder.php

* Partially addresses #712
* Should make the specific inconsistent behavior discussed in PR #2583 impossible to build

Force $_SESSION['user_id'] to be int or NULL before it's passed to any game engine functions

---

src/engine/BMDie.php
src/engine/BMSkillDoppelganger.php
src/engine/BMSkillTurbo.php
test/src/api/responder03Test.php
test/src/api/responderTestFramework.php

Fixes #1663. This is the last unimplemented part of #2629.
This will need a responder test to lock in the new behaviour.

Allow reroll of doppelganger-copied mad/mood dice

---

src/engine/BMDie.php
src/engine/BMFlagIrrelevantForInitiative.php
src/engine/BMGame.php
src/ui/gui.css
src/ui/js/Game.js
test/src/api/responder02Test.php
test/src/api/responder03Test.php
test/src/engine/BMFlagIrrelevantForInitiativeTest.php
test/src/ui/js/test_Game.js

Fixes #835.
On my system, the updated display looks like this:
Let me know what you think about how this looks.

Visually indicate that die is irrelevant for initiative

---

src/engine/BMInterfaceGame.php

Fixes #2685.
I presume this is all that needs to happen to fix the issue, but it'll need testing from an API client.

Changed exception to error message when reactToNewGame receives a false input argument

---

src/ui/js/Env.js
src/ui/js/Faq.js
src/ui/js/Forum.js
test/src/ui/js/test_Faq.js

Fixes #2460. Fixes #2461.
We'll need to test that the relative link I've used here actually works correctly on a deployed server.

Removed "Forum thread: " text from forum links and updated help

---

src/engine/BMDB.php
src/engine/BMExceptionDatabase.php
src/engine/BMInterface.php
src/engine/BMInterfaceHistory.php
test/src/engine/BMDBTest.php
test/src/engine/BMExceptionDatabaseTest.php
test/src/engine/TestDummyPDOConn.php
test/src/engine/TestDummyPDOStatement.php

Don't merge this yet, because it'll need a rebase.
This is intended to be a version of #2628 which can be merged without interfering with tournaments, and will give me a framework to build on driving down (int) casts across the codebase.
------------------------------------------------------------------------
First commit, just implement BMDB:
* BMDB implements a couple of types of select
* No callers invoke BMDB yet --- that will happen in future PRs
* Functions are fully tested using dummy DB connector objects
------------------------------------------------------------------------
Second commit, use BMDB to model all database accesses in BMInterfaceHistory.php
* All `(int)` casts are removed, because the database row selects now take care of them
* All direct accesses to `self::$conn` …

Add simple BMDB layer which casts selected values to consistent types

---

src/ui/js/Newgame.js

Fixes #1010.
I've tested this with Limax: (W) om(34) (T). The selection remains there if I filter according to die skill = ornery or morphing or ANY, but not if I select some other skill.

Made selected button persistent on filter change

---

deploy/circleci/audit_php_files.php
src/api/ApiResponder.php
src/engine/BMDB.php
src/engine/BMInterfaceGameChat.php
src/engine/BMInterfacePlayer.php
test/src/api/responder01Test.php
test/src/engine/BMInterfacePlayerTest.php

* Partially addresses #712
* This change is effectively a noop --- it does select `player_fanatic_id` as NULL rather than 0 (which required a unit test change), but that field is not used by anything and is never set (it is NULL for 100% of players on the prod and staging sites) and IMO it's fine for us to select it as NULL if it's NULL
* It also fixes the setChatVisibility handling in ApiResponder to expect a bool rather than a string.  I'm surprised the string handling was even working, given that the ApiSpec configuration definitely means it's getting a bool.  PHP is very weird.  Anyway, by my testing it works just fine with a bool.
* I added update functionality to BMDB for this change --- nothing in BMInterfacePlayer.php required that functionality to do anything special, so i just …

Migrate BMInterfacePlayer and BMInterfaceGameChat to use BMDB

---

deploy/vagrant/modules/buttonmen/manifests/init.pp

This is the change that should mean i won't have to manually update the site type in Config.js for staging on the next BM release.

Add --follow-symlinks flag to sed commands for staging site (and deprecated dev site)

---

src/api/ApiResponder.php
src/database/mysql.inc.php

* Retry establishing the database connection a few times
* In the worst case, catch exceptions in ApiResponder to avoid returning stacktraces
* Fixes #2707

Handle database exceptions more cleanly

---

deploy/vagrant/manifests/init.pp
deploy/vagrant/modules/apache/manifests/init.pp
deploy/vagrant/modules/fqdn/manifests/init.pp
deploy/vagrant/modules/fqdn/templates/from_ec2_tags.erb

Support SSL on AWS-based buttonmen sites

---

deploy/vagrant/modules/fqdn/templates/from_ec2_tags.erb

I thought i implemented the FQDN stuff in a way that would keep working on virtualbox, but i got my wires crossed and accidentally broke it.  This one-liner fixes it (so virtualbox sites come up, which is the important part, and define the default/fake FQDN `sandbox.buttonweavers.com` and thus don't try to configure HTTPS).

Don't use the ec2_placement_availability_zone variable unless we're on an EC2 instance

---

src/ui/js/Env.js
util/grunt/package.json

* Fixes #2728 
Simply upgrading various package versions addresses the 404 errors, but yields:
```
Running "jshint:all" (jshint) task
../../src/ui/js/Env.js
3 |  var Env = {};
^ 'Env' was used before it was defined.
>> 1 error in 25 files
Warning: Task "jshint:all" failed. Use --force to continue.
```
Setting `"latedef": false` in our preferences would make that error go away, so we could always fall back to that if this doesn't work.
But looking at it, the *only* problem is `Env`, and the only reason we have to check whether `Env` is defined before defining it, is that the JS unit tests use an `Env` property to define the fact that they are running under unit test.  That's kludgy in itself and we could probably do better, but it doesn't really matter --- as far as i can tell, we can …

Upgrade various modules so that jshint can run/pass

---

src/engine/BMInterfaceGameAction.php
test/src/api/responder01Test.php

* Fixes #2734
The responder test change makes a round end in a draw, so i was able to verify that it would have failed with an internal error before this bug was fixed.

Fix end_draw action log load regression

---

src/engine/BMInterfaceGame.php

* This way we'll error out on site type before inspecting the recipes
* Fixes #2757 
I'm going to go ahead and setup a dev site for this, and we can check it out there.

Check whether site allows CustomBM as the first step of are_custom_recipes_valid()

---

src/engine/BMInterfaceGame.php

Fixes #2762.
This unblocks game creation, and still maintains a restriction on creating games with CustomBM if the site is not a development site.
@cgolubi1, I think this needs to be approved urgently, assuming you're happy with it and your tests of CustomBM still pass.

Fixed bug with game creation being blocked by CustomBM checking

---

src/engine/BMInterface.php

This pull request attempts to address the race condition that we think is occurring in #2749 by wrapping almost all of BMInterface->save_game() in a transaction.
I'm guessing that we'll just want to let RandomAI test this a bit to see if this changes any behaviour.

Wrapped save_game in a transaction

---

test/src/api/responder00Test.php
test/src/api/responder03Test.php
test/src/api/responderTestFramework.php

This is my proposed fix for the fact that no tests alerted us to #2762
Had we had this change in place when i introduced the initial syntax for the CustomBM change, responder tests would have lit up:
```
$ sudo /usr/local/bin/create_buttonmen_databases && sudo -u vagrant phpunit --bootstrap /usr/local/etc/buttonmen_phpunit.php /buttonmen/test/src/api/
...
FAILURES!
Tests: 107, Assertions: 625, Failures: 71, Skipped: 5, Incomplete: 3.
```

Run most responderTests on a production site_type

---

src/engine/BMInterface.php

* Fixes #2769 
This isn't a very exciting fix, but it should solve the general problem of preventing the backend from reporting success to players when game save fails (or at least push it one layer up the stack; the calling function could catch and ignore exceptions, but i believe most API functions should return failure when they catch an exception.  Definitely `submit_die_values()` does the right thing, and that's the case for which i filed the issue.

save_game should throw an exception when it fails to save the game

---

src/engine/BMDieOption.php
test/src/engine/BMDieOptionTest.php

Fixes #2486. Fixes #2614.
~~The proposed fix in this pull request uses a non-typed comparison for the option die value. This will need to be strengthened once we are a bit further down the road with ensuring correct typing in the BMInterface* classes (cf. #2628).~~
This pull request was designed to fix the underlying bug with zero-sided option dice without conflicting with the custom recipe pull request (#2389), which disables 0-sided option dice explicitly.
Once both this pull request and #2389 have been accepted, the plan would be to submit another pull request that removes the explicit rule banning 0-sided option dice, and simultaneously removes the special skill flag for my fanatic, which has a (0/4) die.

Fixed zero-sided option die min value

---

deploy/vagrant/setup_aws_vagrantfile

* This forces folder sync to use rsync, rather than attempting SMB sync
See https://github.com/mitchellh/vagrant-aws/issues/365 for what happened when i tried running with a newer vagrant without this configuration.
I have no reason to believe this won't work for anyone else, but IMO this doesn't need any other testing or validation, because i think i'm the only person who's actively using `setup_aws_vagrantfile`

Newer vagrant versions require additional AWS config

---

deploy/vagrant/manifests/init.pp

Testing done: without this change, a build of a fresh AWS site fails with:
```
==> default: Error: Could not find dependency Exec[fqdn_populate_etc_file] for Exec[apache_certbot_setup] at /tmp/vagrant-puppet/modules-01f9aab119b6a4b76e30e7c1575836eb/apache/manifests/init.pp:96
```
With this change, it succeeds.  Sorry again!

Undo accidental removal of FQDN config

---

deploy/vagrant/modules/apache/templates/site_default.erb
deploy/vagrant/modules/buttonmen/templates/apache.conf.erb
deploy/vagrant/modules/buttonmen/templates/backup_database.erb
deploy/vagrant/modules/buttonmen/templates/create_databases.erb
deploy/vagrant/modules/buttonmen/templates/create_rds_database.erb
deploy/vagrant/modules/buttonmen/templates/mysql_root_cli.erb
deploy/vagrant/modules/buttonmen/templates/test_config.erb
deploy/vagrant/modules/fqdn/templates/from_ec2_tags.erb
deploy/vagrant/modules/postfix/templates/main.cf.erb

This one isn't *so* critical, but it's a noop which cleans up an annoying warning that shows up when i run vagrant provision:
```
==> default: Running provisioner: puppet...
==> default: Running Puppet with init.pp...
==> default: Warning: Variable access via 'puppet_hostname' is deprecated. Use '@puppet_hostname' instead. template[/tmp/vagrant-puppet/modules-71904193657bd9e6560c6f15cd46d302/postfix/templates/main.cf.erb]:22
==> default:    (at /usr/lib/ruby/vendor_ruby/puppet/parser/templatewrapper.rb:77:in `method_missing')
==> default: Notice: Compiled catalog for ip-10-153-208-25.ec2.internal in environment production in 1.03 seconds
```
(The warning shows up in the circleci output too, so we should be able to use circleci to verify that we got all the relevant ones.  It only shows …

Clean up how puppet variables are referenced in templates

---

deploy/vagrant/modules/buttonmen/templates/test_config.erb

I was a little hasty in writing up the config check to detect site-type misconfigurations between DB and JS.  For an RDS database like staging, the cron job fails with:
```
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [ERROR] unknown variable 'set-gtid-purged=OFF'
site_type configuration mismatch between database and config file
* database contains:
* /var/www/ui/js/Config.js contains: staging
```
and that blank entry is because the select is failing:
```bash
$ MYSQL_ARGS="-u ${BM_DB_ADMIN_USER} -p${BM_DB_ADMIN_PW} -h ${BM_STAGING_RDS_HOST} --set-gtid-purged=OFF"
$ echo "select conf_value from config where conf_key='site_type'" | mysql -N ${MYSQL_ARGS} ${DBNAME}
mysql: [Warning] Using a password on the command line interface can be insecure. …
```

Don't use --set-gtid-purged flag when querying remote BM database for config

---

deploy/circleci/audit_php_files.php
src/engine/BMAttack.php
src/engine/BMDie.php
src/engine/BMDieOption.php
src/engine/BMDieSwing.php
src/engine/BMGame.php
src/engine/BMInterface.php
src/engine/BMInterfaceGameChat.php
src/engine/BMPlayer.php
test/src/api/responder00Test.php
test/src/ui/js/test_Api.js

* Refactor die parsing slightly so that validate_die_size() does all interaction with the die size as a string, including casting it to an int
* Also remove some bool casts which are not necessary under BMDB
* Fixes #712 (finally!  i think!)

Remove remaining unnecessary int casts from game/recipe/die code

---

deploy/vagrant/modules/apache/templates/monitor_apache_logs.erb

I realised recently that all the errors recorded by our site PHP code contain the string `[:error]`, whereas errors thrown by other things within apache are `[core:error]` or `[authz:error]` or `[mpm_prefork:notice]` or whatever.  I only want to see the PHP errors, because the purpose of this log grep is to detect code/database problems.
Testing:
* ran this script against a couple of sites to make sure it was valid, including a replay site that had a bunch of database connection failures (and they did all show up as expected)
* did a bunch of poking through my e-mail archives of log error greps to validate the assertion that of the spurious errors i've been excluding, only `" not found or unable to stat"` shows up under `[:error]`

Improve apache log grep to only look at PHP errors

---

tools/api-client/python/lib/random_ai.py

In testing #2800, RandomAI failed with the following crash:
```python
Starting game 96
Traceback (most recent call last):
File "./test_log_games", line 71, in <module>
c.log_test_game(i, button1, button2)
File "lib/random_ai.py", line 1803, in log_test_game
self.next_game_action()
File "lib/random_ai.py", line 1787, in next_game_action
if state == 'START_TURN': self._game_action_start_turn()
File "lib/random_ai.py", line 1668, in _game_action_start_turn
self.loaded_data['playerDataArray'][1])
File "lib/random_ai.py", line 1581, in _game_action_start_turn_player
retval and retval.message or "NULL"))
File "lib/random_ai.py", line 1683, in bug
raise ValueError, message
ValueError: API submit_turn(96, 0, 1, {'playerIdx_1_dieIdx_0': 'true', 'playerIdx_0_dieIdx_0': 'true', …
```

RandomAI should handle trip attacks with ht(0) attacking die

---

src/engine/BMInterfaceGame.php
test/src/api/responder00Test.php

* Partially addresses #2827 
Note: i added the test before fixing the code, and verified that the test would catch the internal error:
```
chaos@ubuntu-xenial:/buttonmen/src$ sudo /usr/local/bin/create_buttonmen_databases && sudo -u vagrant phpunit --bootstrap /usr/local/etc/buttonmen_phpunit.php --group fulltest_deps /buttonmen/test/src/api/
buttonmen already exists
buttonmen_test already exists - recreating it
Creating buttonmen_test
Populating buttonmen_test
mysql: [Warning] Using a password on the command line interface can be insecure.
PHPUnit 5.1.3 by Sebastian Bergmann and contributors.
.Caught exception in BMInterface::dismiss_game: Found non-set value in DB when expecting integer
F                                                                  2 / 2 (100%)
Time: 1.33 seconds, …
```

Throw a clean error when dismissing a game in which you're not a participant

---

tools/api-client/python/lib/random_ai.py

Without this fix, my testing for #2067 failed with:
```python
...
Starting game 87
Traceback (most recent call last):
File "./test_log_games", line 71, in <module>
c.log_test_game(i, button1, button2)
File "lib/random_ai.py", line 1820, in log_test_game
self.next_game_action()
File "lib/random_ai.py", line 1804, in next_game_action
if state == 'START_TURN': self._game_action_start_turn()
File "lib/random_ai.py", line 1668, in _game_action_start_turn
self.loaded_data['playerDataArray'][1])
File "lib/random_ai.py", line 1568, in _game_action_start_turn_player
[attacker_indices, defender_indices] = getattr(self, chosenAttackFunction)(b, attackerData, defenderData)
File "lib/random_ai.py", line 1288, in _game_action_start_turn_find_attack_Trip   
self._is_valid_attack_of_type_Trip)
File …
```

RandomAI's max-possible-side-count calculation should treat Mad and Mood like Turbo

---

deploy/vagrant/modules/buttonmen/templates/backup_database.erb
deploy/vagrant/modules/buttonmen/templates/create_rds_database.erb
deploy/vagrant/modules/buttonmen/templates/mysql_root_cli.erb
deploy/vagrant/modules/buttonmen/templates/test_config.erb

We currently get e-mails every day from the prod and staging backup and config-test executions, because we're specifying an admin password on the CLI.  As always, i'd find it easier to contemplate staying on top of buttonmen automated e-mail if we didn't get garbage messages every day.
The simplest MySQL-approved solution for this is to use a INI-format `.cnf` file instead of a bash-format creds file, to hold the username and password.

use a mysql-approved cnf file to hold RDS credentials to suppress CLI warnings

---

deploy/amp/database_initialise.php
src/api/api_core.php
src/engine/BMAttack.php
src/engine/BMInterface.php
src/engine/BMInterfaceGameChat.php
src/engine/BMSkillMaximum.php
src/engine/BMSkillMood.php
src/engine/BMSkillWarrior.php

I've just installed a new version of WAMP on the computer that I'm using to travel to Europe and the U.S.
After managing to get everything running (which was a bit of a headache, since things have changed since the wiki page was written), I noted that unit tests were failing catastrophically and the database_initialise.php script was also failing.
The major issues are that:
- PHP 7.4.x is stricter than previous versions in the way that it deals with non-existent array elements, throwing an error now (see the first point at https://www.php.net/manual/en/migration74.incompatible.php)
- MySQL 8.0.28 upwards changes the default encoding of UTF from a 3 byte to a 4 byte representation (see https://dev.mysql.com/doc/refman/8.0/en/charset-unicode-utf8mb3.html), which causes some of our …

Made changes to enable upgrade to PHP 7.4.33 and MySQL 8.0.31

---

tools/api-client/python/replay_loop

As described by the new header comments, local replaying is useful functionality because it will catch the case in which the new code works, but can't be responder-tested without changes to `responderTest` code.  Right now, we have to catch that manually, or the hard way after pushing the code, but with this flag, e.g. we can test some wildcard games and see the evidence that responderTest can't yet handle Wildcard, without manual hackeration:
```
About to execute: sudo -u ubuntu sh -c "phpunit --bootstrap /usr/local/etc/buttonmen_phpunit.php --group fulltest_deps /buttonmen/test/src/api/ 2>&1" | tee /srv/bmgames/chaos-test/replay_state/ip-172-31-33-91/1ab6dda9cea5063c2b10e9e6042092b7a62a160c.games.20230126.225110.tar.bz2.output
PHP Parse error:  syntax error, unexpected 'suit_black' …
```

Add replay support for locally replaying the games that were just generated

---

.circleci/config.yml
deploy/circleci/manifests/init.pp
deploy/vagrant/manifests/init.pp
deploy/vagrant/modules/buttonmen/manifests/init.pp
deploy/vagrant/modules/buttonmen/templates/run_buttonmen_tests.erb
test/tools/api-client/README
test/tools/api-client/python/lib/test_bmapi.py
tools/api-client/python/README.md
tools/api-client/python/lib/bmapi.py
tools/api-client/python/lib/bmutils.py
tools/api-client/python/replaytest/README.md
tools/api-client/python/replaytest/prep_replay_games
tools/api-client/python/replaytest/replay_loop
tools/api-client/python/replaytest/replay_single_game
tools/api-client/python/replaytest/test_log_games
tools/api-client/python/replaytest/update_replay_games
tools/api-client/python/requirements.txt

This partially reproduces Dan Langford's python3 support PR #2667
Specifically, this PR includes:
* make `bmapi.py` and `bmutils.py` syntactically compatible with python3
* move to the use of a `requirements.txt` file for dependencies
* use vagrant to install python27 and python39 on all BM sites (using miniconda for simplicity)
* update buttonmen tests of `bmapi.py` to run using both python27 and python39, either locally or via CircleCI
* move replaytest wrappers (but not `random_ai.py`) into their own directory, and update their paths to use the conda python27 installation
This PR does *not* include:
* A broader reorg of the python files for path cleanliness
* Any updates of replay scripts or `random_ai.py` to support python3 or PEP
* Any updates of the user scripts to support python3 …

Make bmapi compatible with python3

---

deploy/vagrant/modules/buttonmen/manifests/init.pp

If this passes CircleCI, that's evidence that it works around the recent miniconda change and fixes #2887 (though presumably they'll eventually remove the version we're hardcoding, so we'll have to go back to using a newer version eventually).

Hardcode a known-working version of miniconda

---

.circleci/config.yml
deploy/vagrant/modules/buttonmen/manifests/init.pp
deploy/vagrant/modules/buttonmen/templates/run_buttonmen_python_tests.erb
deploy/vagrant/modules/buttonmen/templates/run_buttonmen_tests.erb
test/tools/api-client/python/lib/dummy_bmapi.py
test/tools/api-client/python/lib/script_test_helpers.py
test/tools/api-client/python/lib/test_bmapi.py
test/tools/api-client/python/lib/test_bmutils.py
test/tools/api-client/python/lib/test_buttons_with_skills.py
test/tools/api-client/python/lib/test_create_game.py
test/tools/api-client/python/lib/test_game_create.py
test/tools/api-client/python/lib/test_game_data.py
test/tools/api-client/python/lib/test_game_info.py
test/tools/api-client/python/lib/test_head_to_head.py
test/tools/api-client/python/lib/test_record.py
tools/api-client/python/buttons-with-skills
tools/api-client/python/game-create
tools/api-client/python/game-data
tools/api-client/python/head-to-head
tools/api-client/python/lib/bmutils.py
tools/api-client/python/record

I think this pulls a good number of other pieces from #2667 in a way that's not intrusive to replay testing.
Basically what this PR does is add very bare-bones "is it on?" unit testing to bmutils and to *most* of the convenience API client utilities (everything except `monitor` and `interactive_mode.py`), and plug it into a wrapper that circleci runs on python27 and on python39.
So it fixes a couple of python3 incompatibilities in various things, but mostly it unblocks the way for people to add more functionality to the API, and more scripts, and use unit testing to verify that they are more-or-less compatible with both python versions.
The only testing i did is that the unit tests pass, but i think that's sufficient for what we're doing here --- replay testing doesn't use any of these …

Expand python unit testing to cover bmutils and several of the scripts

---

src/ui/js/About.js
src/ui/js/Login.js
src/ui/js/Overview.js
test/src/ui/js/test_Login.js

Partially resolves Issue #2891 for the moment, while cheapass.com remains in flux.
This pull request deliberately does the minimal necessary to either remove dead links to cheapass.com or change them to the http version, which currently correctly redirects to https://crabfragmentlabs.com.
We may potentially need to update the links in three months or so, when things are clearer on what's going on with cheapass.com (as per email from James Ernest)

Fixed or removed links to cheapass.com

---

Dockerfile
deploy/docker/buttonmen_ecs_config.json
deploy/docker/deploy_buttonmen_site
deploy/docker/startup.sh
deploy/vagrant/manifests/init.pp
deploy/vagrant/modules/buttonmen/manifests/init.pp
deploy/vagrant/run_puppet.sh

This partially addresses #2908 - specifically it adds support for using an ECS site with a remote database, which is required by staging and prod
* As part of this PR, i cleaned up the places in the existing vagrant config where we hardcode locations and names of specific buttonweavers sites, because all of that will be handled by the config file in the future
* I also made the container startup able to handle the case in which the container doesn't have mysqld installed, which is the case for remote-db sites
* I also fixed an unrelated bug where puppet failures didn't cause the overall container deployment to fail fast, leading to harder-to-diagnose problems using the image
I tested this by creating a dev site using a remote DB and this codebase, and then rebuilding that dev site using a …

Add support for ECS sites with remote databases

---

deploy/docker/teardown_buttonmen_site

* Part of development work for #2908 
This is just a script for me to use to teardown a dev site once we're done testing with it --- it cleans up ECS tasks (which cost money), ECS services (which are confusing to have lying around in the cluster), and ECR repositories (which cost money).  It doesn't bother to remove DNS entries or ECS task definitions, which i believe are not billed at any scale we're likely to hit, and which aren't in the way.
Before tearing anything down, it downloads the most recent DB backup of the dev site, in case we need it for anything later.
[I tested it by using it to tear down the dev-cgolubi1-2908_remote_db site.]

Script to teardown AWS resources for a dev site

---

deploy/docker/buttonmen_ecs_config.json
deploy/docker/deploy_buttonmen_site
deploy/vagrant/modules/buttonmen/manifests/init.pp

Partially addresses #2908 
Note: the creation and configuration of the NLB itself is not part of this code.  The NLB has to have:
* A mapping in the AZ in which the ECS service's subnet is located, attached to the EIP whose DNS FQDN is the `bmsite_fqdn` used in the configuration here
* Two attached port forwardings, one for each of two target groups, one on port 80 and one on port 443.  (The ARNs of the two target groups must be the `nlb_arn_port_80` and `nlb_arn_port_443` used in the configuration here.)
Configuring the ECS service to use the target groups, means that new containers will be registered with those target groups, and unhealthy container deregistered.
I also fix a regression with the `set_buttonmen_config` change in my previous PR --- obviously in the case in which we're …

Add support for attaching containers to an NLB so they can be used with an elastic IP

---

deploy/docker/buttonmen_ecs_config.json
deploy/docker/deploy_buttonmen_site

* Partially addresses #2908 
Working test site at https://2908-cloudwatch-logs.cgolubi1.dev.buttonweavers.com/
In cloudwatch logs, i have a logstream `2908-cloudwatch-logs.cgolubi1.dev.buttonweavers.com/buttonmen/8b45298b5efc4c4dbc85b2da6e07e30b` with contents:
```
timestamp,message
1708390751890,'"+ /etc/init.d/rsyslog start"
1708390751919, * Starting enhanced syslogd rsyslogd
1708390752041,   ...done.
1708390752041,'"+ /etc/init.d/cron start"
1708390752047, * Starting periodic command scheduler cron
1708390752052,   ...done.
1708390752052,'"+ /etc/init.d/ssh start"
1708390752170, * Starting OpenBSD Secure Shell server sshd
1708390752190,   ...done.
1708390752223,'"+ /etc/init.d/postfix start"
1708390752226, * Starting Postfix Mail Transport Agent postfix
1708390753230,   ...done. …
```

Use ECS awslogs driver to log startup script output to cloudwatch

---

deploy/docker/deploy_buttonmen_site
deploy/vagrant/manifests/init.pp
deploy/vagrant/modules/buttonmen/manifests/init.pp
deploy/vagrant/modules/buttonmen/templates/buttonmen_db.cnf.erb

* Partially addresses #2908 
Test site: https://2908-buttonmen-db-cnf.cgolubi1.dev.buttonweavers.com/ui/
Bonus: i've finally updated the database on that site, by uploading the staging DB backup, logging into my new container, and running:
```
$ bzcat staging.sql.bz2 | grep -v 'SQL SECURITY DEFINER' | sudo /usr/local/bin/mysql_root_cli
```
So no more internal errors on the dev RDS DB.  (This is secretly a test of whether `mysql_root_cli` works, of course, which is what this PR is actually about.)

Build buttonmen_db.cnf for remote databases in vagrant, to survive container replacement

---

deploy/docker/deploy_buttonmen_site
deploy/docker/startup.sh

* Partially addresses #2908, specifically "When ECS replaces a site with a remote database, set_buttonmen_config must be run"
Site: https://2908-set-config-on-startup.cgolubi1.dev.buttonweavers.com/ui/
You can see that the site is correctly configured as a "development" type site, and the config sanity check succeeds as well:
```
chaos@ip-10-0-0-8:~$ sudo /usr/local/bin/test_buttonmen_config 
chaos@ip-10-0-0-8:~$ 
```
I tested this using a local database dev site as well, and that seemed to work.

Always set site type config on container startup; only rerun remotely after loading a DB

---

tools/api-client/python/README.md
tools/api-client/python/buttons-with-skills
tools/api-client/python/game-create
tools/api-client/python/game-data
tools/api-client/python/head-to-head
tools/api-client/python/record

Turns out that these were already pretty Python 3 compatible, they just didn't say so at the top; and also, they don't need to import anything from the future now.

Port scripts written by irilyth to Python 3.

---

deploy/docker/buttonmen_ecs_config.json
deploy/docker/deploy_buttonmen_site
deploy/docker/startup.sh
deploy/vagrant/modules/apache/templates/setup_certbot.erb

Partially addresses #2908.
Testing:
* I tried this out both on a standard dev site deployment with no remote database, and on a deployment with a remote database and the EIP `rds.dev.buttonweavers.com` (both torn down now)
* In both cases, i tested the sequence:
* Do an initial deployment
* Do a second deployment to replace the container/task when the site already exists
* Stop the task from within ECS so that the ECS service replaces it
* In all cases, if `/mnt/efs/${FQDN}/letsencrypt/live` didn't exist, the letsencrypt negotiation happened after startup.  If it did exist, negotiation didn't happen, and the existing cert was reused with a message like:
```
Cert not yet due for renewal
Keeping the existing certificate
```
* In the EIP case, all three of the test cases led to a fully …

Containers should mount an EFS filesystem and use it for SSL certs and backups

---

deploy/vagrant/manifests/init.pp
deploy/vagrant/modules/apt/manifests/init.pp
deploy/vagrant/modules/syslog/manifests/init.pp
deploy/vagrant/modules/syslog/templates/rsyslog_rotate.erb

* Also install some packages that are helpful for debugging and don't exist by default on containers
Partially addresses #2908
See comment on that link - https://github.com/buttonmen-dev/buttonmen/issues/2908#issuecomment-2102692586 - for testing done.

Override the rsyslog post-rotate action to work on ECS containers

---

deploy/docker/get_buttonmen_site_ipaddr

This is just a utility for me to use, but it'll help with running post-deploy database updates for future code pushes, which is on the checklist for #2908.
Testing:
```
$ env AWS_PROFILE=bm_deploy /Users/chaos/games/buttonmen/miniconda3/bin/python ./deploy/docker/get_buttonmen_site_ipaddr 
54.165.109.196
```
That matches what i get from DNS (but note that DNS only works because the container hasn't been replaced since DNS was set, and won't work for staging or prod --- this should):
```
$ host 2908-get-ipaddr-script.cgolubi1.dev.buttonweavers.com
2908-get-ipaddr-script.cgolubi1.dev.buttonweavers.com has address 54.165.109.196
```

Script to print the IP address of this buttonmen site's launched container

---

deploy/docker/get_buttonmen_site_ipaddr

* Fixes #2949 
With this change, `get_buttonmen_site_ipaddr` works in my staging and production working directories.
Apologies for the bother!

Fix repo regexp in get_buttonmen_site_ipaddr to work for staging and prod

---

deploy/docker/buttonmen_ecs_config.json
deploy/docker/deploy_buttonmen_site
deploy/docker/get_buttonmen_site_ipaddr
deploy/docker/startup_replay.sh
deploy/docker/teardown_buttonmen_site
tools/api-client/python/replaytest/replay_loop

* Partially addresses #2908 
This adds support for a "replay" site type, which can be invoked with a flag (`-p`) to `deploy_buttonmen_site`.
* replay sites have a simpler startup than dev/staging/prod sites --- they don't setup HTTPS, they don't have the option of using a remote database, etc
* i made some changes to replay_loop to work more consistently in the constrained container environment:
* restart mysql and apache between test runs, for consistency
* log information about novel games that were played, for debugging
I've tested:
* dev sites still work, and a dev and replay site can be deployed for the same branch at the same time without conflicts
* replay testing generally works, and in particular ran for 22 hours without interruption

Minimal container support for replay sites

---

tools/api-client/python/replaytest/replay_single_game

Partially addresses #2908 
Without this fix:
```
$ /buttonmen/tools/api-client/python/replaytest/replay_single_game 183c998516ec4aaa04622691ad4e5c8439c56267.games.20240524.014140.tar.bz2 00020
sudo: unknown user: ubuntu
sudo: unable to initialize policy plugin
command failed: sudo -u ubuntu rm -f /buttonmen/test/src/api/responder99Test.php
```
With this fix:
```
$ /buttonmen/tools/api-client/python/replaytest/replay_single_game 183c998516ec4aaa04622691ad4e5c8439c56267.games.20240524.014140.tar.bz2 00020
<?php
require_once 'responderTestFramework.php';
class responder99Test extends responderTestFramework {
Updating and prepping game for replay from: ./output/game00020.pck
About to execute: sudo -u root sh -c "phpunit --bootstrap /usr/local/etc/buttonmen_phpunit.php --group fulltest_deps …
```

Update replay_single_game to set the correct username for container execution

---

deploy/docker/deploy_buttonmen_site

This is the first step towards helping devs who have dockerd installed locally start test sites.
```
$ /Users/chaos/games/buttonmen/miniconda3/bin/python ./deploy/docker/deploy_buttonmen_site -l -u
...
About to run docker image locally: ['docker', 'run', '--init', '-d', '-p', '8080:80/tcp', 'local-cgolubi1/local_docker_deploy:5e24231b', '/bin/bash', '/buttonmen/deploy/docker/startup_replay.sh']
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
e4da2bd401c8337e70bb7b43a7a0379cae1eeb5f1d4da65f7cba6cf0552e9877
Site is running locally!  Useful docker commands:
* docker ps: find the ID of the running container
* docker logs <ID>: find startup logs of a container (e.g. to diagnose a container …
```

Add support for building a docker container and starting it locally

---

src/engine/BMDieOption.php

Addresses part of #2772.
The aim of this pull request is to simply re-enable zero option dice. Since we currently have no enabled recipes involving zero option dice, this should not affect the prod site at all.
We already have a low-level test that was added as part of #2641 that checks that an option die sets correctly to zero (i.e., value = 0, max = 0, min = 0).
Thus, the direct effect of this change would be to make zero option dice available for use via CustomBM. If we do move towards adding a recipe with a zero option die, we would follow our standard procedure of testing with RandomAI, as well as adding an appropriate responder test to make sure that the zero option die works correctly.
[Dev site at: https://2773-reenable-custombm-zero-option.blackshadowshade.dev.buttonweavers.com/ui …

Re-enabled zero option dice for CustomBM

---

src/engine/BMInterfaceGame.php

* Partially addresses #2967 
This is the simplest possible fix for the root cause.
Background:
* Fire-assisted attacks are performed in two parts, first setting up the attack for fire turndown, and then the fire turndown happens and the attack is committed
* Setting turbo values always happens after the attack is resolved.
* Because in the UI the turbo values are set on the first screen, we cache those values from `submitTurn`, and then get them out of the cache and apply them when we adjust fire dice.
The reason we get games into a broken state, is simply that the fire-adjusted path has its own implementation of applying turbo values, and it doesn't check the return value from `set_turbo_sizes()`, such that if `set_turbo_sizes()` fails, we just plow on ahead, and importantly, we plow on …

Avoid putting the game in a broken state if invalid turbo settings are submitted for fire-assisted attack

---

src/api/ApiResponder.php

* Fixes #2983 
Testing:
* I did a bit of manual testing, which i'll describe in a comment
* There's a dev site so people can poke around --- this should be a noop; we're not aware of anything that happens on a normal site that should lead to blank pages, so i really just want a smoke test of normal site activity: https://2983-json-encode-logging.cgolubi1.dev.buttonweavers.com
* I stood up a replay site, because testing of novel games uses the API, so if anything goes wrong during gameplay, it should show up in those logs

Log error message on API response json_encode() failure

---

src/engine/BMInterfaceGame.php
test/src/api/responder04Test.php

Fixes #2687. Fixes #2989.
This pull request implements an explicit check of the submitted attack type. If the attack type is not 'Default' or 'Surrender', it checks whether the attack type is one of the valid attack types and if not, rejects the submitted attack.
Ideally, to verify that this solution fixes both issues, we should get BMAI to submit the attacks that it has attempted to submit and check that they both now fail. However, if this is too difficult, then getting RandomAI to do the same should suffice.
Dev site: https://2989-invalid-pass.blackshadowshade.dev.buttonweavers.com/

Added check that a submitted attack type is valid

---

src/engine/BMInterfaceForum.php
test/src/api/responder00Test.php

* Fixes #2993 
The player-visible change here is trivial --- a marginally friendlier message.  The purpose of the fix is to make it so that a player requesting a non-existent forum thread doesn't cause an error log message, which it shouldn't, because only internal errors should cause error log messages.
I don't think this needs a dev site --- i think the extra responder test stub plus the screencap i'm going to put in a comment demonstrates that it works, and it's not worth more discussion than that.  But let me know if you think more is needed!

Explicitly handle the case where a player requests a non-existent forum thread

---

src/engine/BMInterfaceNewuser.php

* Fixes #2977 
This is the simplest fix for the issue i could think of.
We don't have a very well-defined goal in limiting the number of new user creation requests --- it's just that user creation and password reset verification are parts of the site that can be accessed without an account, so they're relatively more DoS-prone than most of the site for which you have to be logged in.
So "no more than 5 new accounts within 15 minutes" is completely arbitrary, but IMO it's better to have some speedbump than none, and the details don't matter very much.
I'm standing up a dev site for this, and also did some local testing, which i'll describe in a comment to the PR.
Dev site: https://2977-account-creation-ipaddr-check.cgolubi1.dev.buttonweavers.com/ui/

Replace the check for new accounts from the same IP address, with a check for too many new accounts in the past 15 minutes

---

tools/api-client/python/lib/random_ai.py
tools/api-client/python/replaytest/replay_loop

* Add replay_loop --test-output, which nondestructively replay-tests whatever happens to be in the output directory right now
* Add random_ai support for initializing a new game's data object in a more readable way, by leaning on existing diff methods
* replay_loop should error out immediately if prep_replay_games fails
This partially addresses #2953; in particular it adds the flag to nondestructively test whatever is in output/ right now, and reduces the work needed to turn test output into a responderTest to much closer to zero.
I've tested the new flags manually, and played about 900 novel and replayed games, and i'm satisfied with the changes.

Implement some improvements to random_ai and replay_loop

---

deploy/docker/deploy_buttonmen_site
deploy/docker/get_buttonmen_site_ipaddr
deploy/docker/teardown_buttonmen_site

* Support parsing either SSH or HTTPS git remotes
* Fix escaping of regexps for newer python versions
* Import boto3 just-in-time because it's not needed for local containers
These changes are to support blackshadowshade's testing, and also partially cover #2973.

Minor fixes to docker deployment scripts

---

deploy/vagrant/modules/buttonmen/manifests/init.pp
deploy/vagrant/modules/buttonmen/templates/sync_web_files.erb

* Fixes #3007 
I tested that `deploy_buttonmen_site -l` still works for me with this change.
Shadowshade, want to test that it solves your deployment problem before accepting?  With this change, you should be able to deploy a container site and it should be accessible via web UI, without any hand-modification needed.

Set file modes correctly when copying files from /buttonmen to /var/www

---

deploy/database/updates/scripts/02974_fix_nonascii
deploy/vagrant/modules/buttonmen/manifests/init.pp
deploy/vagrant/modules/buttonmen/templates/branch_database_rebuild_test.erb
deploy/vagrant/modules/buttonmen/templates/buttonmen_mysqldb_27.py.erb
deploy/vagrant/modules/mysql/templates/buttonmen.cnf.erb

* Use latin1 encoding in local databases by default
* Add script to fix wrongly-encoded fields in a live DB
* Infrastructure fixes needed for the script to run:
* Implement generic python MySQLdb connector for buttonmen DBs
* Fix bug where branch database test fails if update scripts are defined
This fixes #2974.
When this is deployed to prod and staging, the following actions need to be taken in addition to the deployment:
* Run the update script to repair newer entries (the third line should report no further problems):
```
sudo /buttonmen/deploy/database/updates/scripts/02974_fix_nonascii --dry-run
sudo /buttonmen/deploy/database/updates/scripts/02974_fix_nonascii
sudo /buttonmen/deploy/database/updates/scripts/02974_fix_nonascii --dry-run
```
* Update the live database for the site …

Standardize MySQL database field encoding

---

tools/api-client/python/head-to-head

Fixes #3017.
With this change, the command that currently throws an exception instead says
```
[20:05:30] irilyth@azazel:/home/irilyth/src/github/irilyth/buttonmen/tools/api-client/python
+$ ./head-to-head button Georgia Bauer
Georgia vs Bauer: 0 - 0 (0.00%)
```
as expected and desired.

Handle what amounts to a division-by-zero error when the divisor is 'None'.

---

tools/api-client/python/replaytest/replay_loop

Partially addresses #2953
This addresses an issue in which sometimes mysqld takes more than 2 seconds to stop, so it hasn't stopped yet when the start is attempted, so the start fails, and the replay loop falls over and has to be manually restarted.
I've verified via a replay site that this functionality works in the happy path, and that if i substitute a broken "start" command, the failure case works --- so i didn't break the ability to run test games.  I'm letting it run to see if it helps with the problem, so we could wait a week to approve it, but also it's harmless, so if you want to just go ahead and approve it, i think that's fine too.

When restarting mysqld during replay testing, retry the start a few times

---

src/api/ApiSpec.php
test/src/api/responder00Test.php
test/src/ui/js/test_Overview.js
test/tools/api-client/python/lib/test_bmapi.py
test/tools/api-client/python/lib/test_bmutils.py

* Fixes #3030 
The new responder test checks provide evidence that the fix works.  Without the fix, a similar test shows that game creation succeeds, but the description is corrupted:
```
1) responder00Test::test_request_createGame
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'αααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααα'
+'ααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααα?'
/buttonmen/test/src/api/responder00Test.php:345
FAILURES!
Tests: 2, Assertions: 74, Failures: 1.
```
I also tested manually and found that with the fix, 127 alphas succeed and 128 alphas fail cleanly.  Without the fix, i see a …

Use strlen when testing validity of API string argument length

---

deploy/docker/deploy_buttonmen_site

This has been a papercut for me in standing up dev sites for awhile: sometimes a dev site fails to come up healthy, usually due to intermittent MySQL issues, and the deployment doesn't fail immediately, but just rolls through.  So i have to check for hidden failures on SSH commands, which is tedious.
This PR won't actually address the underlying flakiness problem --- i'll presumably need a new fix for that once i learn more about it --- but it'll make it easier to know when i have to retry.
I tested this by standing up a dev site, which was successful and loaded its database (i could login to it).  I've torn it down now.

When an SSH- or SCP-based command fails, the whole deployment should fail

---

deploy/docker/deploy_buttonmen_site
deploy/docker/startup.sh
deploy/vagrant/modules/apache/templates/setup_certbot.erb

* Also wait for mysqld to startup before running database-related deploy commands
* Fixes #3048

Standardize logic in apache_setup_certbot so certbot only actually runs once per container startup/deploy

---

test/src/api/responderTournamentTest.php
tools/api-client/python/lib/random_ai.py
tools/api-client/python/lib/random_tournament.py
tools/api-client/python/replaytest/replay_loop
tools/api-client/python/replaytest/test_log_tournament

This code should only affect replay testing.  It does:
* Removes a `fulltest_deps` flag which was erroneously left on a test in the previous tournaments PR, which is currently (mildly) breaking replay test of the main branch
* Modifies `random_ai.py` to make replay testing of games involving players other than responder003 and responder004 possible, and to support iterating an in-progress game by a single move, whether or not that move completes the game
* Creates `random_tournament.py` and `test_log_tournament`, which support automated creation and play of random tournaments, including both validation that tournament API calls behave as we've discussed and as documented in the state machine diagram, and validation that tournaments are creatable and tournament games are playable.
* …

Add replay scripts for tournaments
