buttonmen-dev/buttonmen

test/src/api/responderTest.php
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/403/
=> fix gman97216 images in tests

src/ui/js/Api.js, src/ui/js/Overview.js
Fixes #1169.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/571/
=> Reversed display order of games awaiting opponent's action

src/engine/BMSkillTrip.php, test/src/api/responderTest.php
Fixes #1497.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/602/
=> Fixed twin trip bug

src/ui/help/index.html, src/ui/js/Overview.js
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/606/
=> Changed copyright year from 2014 to 2015

test/src/ui/js/test_Overview.js
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/608/
=> Fixed QUnit test for copyright year

deploy/vagrant/modules/jenkins/templates/config.xml.erb
Not bothering to test, because it's a jenkins config-only change.
=> * add nkmcalli job to jenkins config

deploy/vagrant/modules/jenkins/templates/config.xml.erb
=> Give tetujin3d build permissions in jenkins

deploy/database/data.button.sql, deploy/database/updates/00779_03_fixed_redefine.sql, src/engine/BMBtnSkillRandomBMFixed.php, src/engine/BMBtnSkillRandomBMMixed.php, src/engine/BMBtnSkillRandomBMVanilla.php, test/src/engine/BMBtnSkillRandomBMFixedTest.php
Changed the definition of BMRandomFixed to use the same skill on both dice
Requires database update 00779_03_fixed_redefine.sql
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/622/ (assuming it passes)
=> Changed definition of BMRandomFixed

src/engine/BMSkill.php
Fixes #1526.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/627/
=> Removed repeated skills and added missing skill to skill ordering

src/engine/BMAttackTrip.php, test/src/engine/BMAttackTripTest.php
Fixes #1522.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/633/
=> Added logic to disallow trip attacks against too-large maximum dice

src/engine/BMAttackSkill.php, test/src/engine/TestDummyBMAttSkillTesting.php
Fixes #1404.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/635/
=> Sped up checking whether skill attacks are valid

test/src/api/responderTest.php
* Adds a responder test with BMRandomMixed and regression testing for trip attacks against Maximum dice
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/404/ (assuming it passes)
=> trip maximum responder test

test/src/api/responderTest.php
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/405/
=> Add Warrior regression test at the API level

src/engine/BMBtnSkillRandomBMMixed.php
Fixes #1539.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/641/
=> Excluded warrior skill from RandomBMMixed

test/src/api/responderTest.php, test/src/ui/js/BMTestUtils.js, test/src/ui/js/test_Game.js
* Addresses #1468 
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/406/
=> migrate remaining UI tests to use responder tests

src/engine/BMAttack.php, src/engine/BMGame.php, test/src/api/responderTest.php
Fixes #1538.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/643/
=> Fixed determination of possible attack types in the presence of optional attacks

src/engine/BMAttack.php, src/engine/BMAttackDefault.php, src/engine/BMAttackSkill.php, src/engine/BMGame.php, src/engine/BMInterface.php, test/src/engine/BMAttackBerserkTest.php, test/src/engine/BMAttackDefaultTest.php, test/src/engine/BMAttackPassTest.php, test/src/engine/BMAttackPowerTest.php, test/src/engine/BMAttackShadowTest.php, test/src/engine/BMAttackSkillTest.php, test/src/engine/BMAttackSpeedTest.php, test/src/engine/BMAttackSurrenderTest.php, test/src/engine/BMAttackTest.php, test/src/engine/BMAttackTripTest.php
Fixes #1404 better.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/644/
=> Remove singleton from BMAttack, and generate hit table only if it doesn't yet exist

src/ui/js/Game.js
Fixes #1548.
This still requires an appropriate QUnit test.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/651/
=> Defender's warrior dice are now greyed out and not clickable

test/src/api/responderTest.php
* Prereq for pull #1546 to work on vagrant
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/408/
=> responderTest setup should create directory for loadGameData API output files if it doesn't exist already

test/src/ui/js/BMTestUtils.js, test/src/ui/js/test_Game.js
* Fixes #1553
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/409/
=> Add a QUnit test for greyed warrior dice

src/engine/BMAttackSkill.php, src/engine/BMUtilityHitTable.php
Fixes #1534.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/642/
=> Added documentation to BMAttackSkill

src/engine/BMSkillBerserk.php, test/src/api/responderTest.php
Fixes #1563.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/653/ (if it passes)
=> Corrected description of berserk

src/ui/gui.css
Addresses #1336.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/652/
=> Shifted "Mark thread as read" to the right hand side

src/engine/BMDieTwin.php, src/engine/BMGameAction.php, test/src/api/responderTest.php
Fixes #1452.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/654/
=> Fixed logging of attacking trip dice that split

src/engine/BMSkillQueer.php, test/src/api/responderTest.php, test/src/engine/BMSkillQueerTest.php
Fixes #1574.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/659/
=> Fixed bug that disallowed queer dice with non-positive integer values

deploy/database/schema.game.sql, deploy/database/updates/01580_database_index.sql
Addresses part of #1580.
Requires database update 01580_database_index.sql
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/670/
=> Added indices to game_action_log and game_chat_log

src/engine/BMDie.php, src/engine/BMGameAction.php
Addresses part of #1580.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/673/
=> BMDie now only reports on die flag information when it is non-trivial

src/ui/gui.css
Reverts pull request #1561.
No Jenkins, since this is a trivial change affecting only CSS.
=> Reverted change to placement of markRead button

src/engine/BMAttack.php, src/engine/BMAttackBerserk.php, src/engine/BMAttackDefault.php, src/engine/BMAttackPass.php, src/engine/BMAttackPower.php, src/engine/BMAttackShadow.php, src/engine/BMAttackSpeed.php, src/engine/BMAttackSurrender.php, src/engine/BMAttackTrip.php, src/engine/BMBtnSkillRandomBM.php, src/engine/BMBtnSkillRandomBMAnime.php, src/engine/BMBtnSkillRandomBMFixed.php, src/engine/BMBtnSkillRandomBMMixed.php, src/engine/BMButton.php, src/engine/BMDie.php, src/engine/BMDieOption.php, src/engine/BMDieSwing.php, src/engine/BMDieTwin.php, src/engine/BMEmail.php, src/engine/BMGame.php, src/engine/BMGameAction.php, src/engine/BMGameState.php, src/engine/BMInterfaceNewuser.php, src/engine/BMSkill.php
Continues to address #1130.
I'm putting this up now so that it has a chance of being accepted in April.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/683/
=> Removed more PHPDoc warnings

notes/engine/List_of_die_hooks_and_skills.txt, src/engine/BMGame.php, src/engine/BMSkillWarrior.php, test/src/api/responderTest.php, test/src/engine/BMGameTest.php, test/src/engine/BMSkillWarriorTest.php
Fixes #1572.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/658/
=> Warrior dice now cannot react to initiative

notes/engine/List_of_die_hooks_and_skills.txt, src/engine/BMDie.php, src/engine/BMSkillMaximum.php, src/engine/BMSkillMood.php, test/src/api/responderTest.php, test/src/engine/BMSkillMaximumTest.php, test/src/engine/BMSkillMoodTest.php
Fixes #1597.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/685/ (if it passes)
=> Disabled Maximum and Mood (and Mad) when a die has Konstant

notes/engine/List_of_die_hooks_and_skills.txt, src/engine/BMDie.php, src/engine/BMSkillMaximum.php, src/engine/BMSkillMood.php, test/src/api/responderTest.php, test/src/engine/BMSkillMaximumTest.php, test/src/engine/BMSkillMoodTest.php
Reverts buttonmen-dev/buttonmen#1601
Accidentally merged while we're in a pull freeze.
=> Revert "Disabled Maximum and Mood (and Mad) when a die has Konstant"

deploy/database/data.button.sql, deploy/database/updates/00779_05_RandomBM.sql, src/engine/BMBtnSkillRandomBMMixed.php, test/src/api/responderTest.php, test/src/engine/BMBtnSkillRandomBMMixedTest.php
Addresses part of #779.
See commit message for details of changes.
Requires database update 00779_05_RandomBM.sql
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/663/ (if it passes)
=> Addresses multiple issues regarding RandomBM

src/engine/BMSkillMood.php, test/src/engine/BMGameTest.php
Fixes #1570.
This will need testing to see how it interacts with radioactive.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/662/
=> Mood now triggers after a split

src/engine/BMSkillChance.php, src/engine/BMSkillFocus.php, src/engine/BMSkillKonstant.php, src/engine/BMSkillMaximum.php, src/engine/BMSkillOrnery.php, src/engine/BMSkillTrip.php, test/src/api/responderTest.php
Fixes #1587.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/686/
=> Made konstant description more precise, and added interaction descriptions

src/engine/BMBtnSkillRandomBMMixed.php, test/src/api/responderTest.php, test/src/engine/BMBtnSkillRandomBMMixedTest.php
Reactivated berserk in RandomBMMixed (#779).
Depends on #1579.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/703/
=> Reactivated Berserk in RandomBMMixed

notes/engine/List_of_die_hooks_and_skills.txt, src/engine/BMBtnSkillRandomBMMixed.php, src/engine/BMDie.php, test/src/api/responderTest.php, test/src/engine/BMBtnSkillRandomBMMixedTest.php
Addresses part of #779.
This will cause a conflict in the unit tests for #1605.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/712
=> Reactivated Mighty and Weak in RandomBMMixed

src/engine/BMGame.php, src/engine/BMInterface.php, test/src/api/responderTest.php
Fixes #1631.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/738/
=> Option dice now work correctly when they are to the right of a reserve die 

src/engine/BMDie.php
Addresses part of #1130.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/726/
=> Clean up PHPDoc warnings for BMDie

src/ui/js/Game.js
Fixes #1244.
I reckon that anything more than this extra link on the End of Game page is overkill. I really don't know whether other New Game links are actually useful, especially since it's possible to change game settings on the Create Game screen.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/721/
=> Added extra link on End of Game game to create new game with random buttons

src/ui/js/Game.js
Fixes #1246.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/720/
=> Fixed redirect location after dismissing a completed game

deploy/jenkins/build.xml
Addresses part of #1130.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/735/
=> Exclude ApiResponder and DummyApiResponder from PHPDoc targets

deploy/database/data.game.sql, deploy/database/updates/00506_boom_01.sql, notes/engine/List_of_die_hooks_and_skills.txt, src/engine/BMAttackBoom.php, src/engine/BMAttackDefault.php, src/engine/BMDie.php, src/engine/BMGame.php, src/engine/BMGameAction.php, src/engine/BMInterface.php, src/engine/BMSkill.php, src/engine/BMSkillBoom.php, src/engine/BMSkillMorphing.php, src/engine/BMSkillStealth.php, src/ui/js/Game.js, test/src/api/responderTest.php, test/src/engine/BMAttackBoomTest.php, test/src/engine/BMBtnSkillRandomBMMixedTest.php, test/src/engine/BMGameTest.php, test/src/engine/BMSkillBoomTest.php, test/src/engine/BMSkillTest.php, tools/api-client/python/lib/bmutils.py
Fixes #506.
This pull request needs additional responder and Javascript tests before it's really complete. Also, the unit tests in BMBtnSkillRandomBMMixedTest.php will conflict with the changes to RandomBM in #1579.
Requires database update 00506_boom_01.sql
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/698/
=> Added boom skill

test/src/api/responderTest.php
Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/412/ (assuming it passes)
=> Add responder test for Boom dice

deploy/database/data.button.sql, deploy/database/updates/01643_mad_order.sql, test/src/api/responderTest.php
Fixes #1641.
Requires database update 01643_mad_order.sql
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/748/
=> Fixed recipes with Mad Swing to use post-fix notation

src/engine/BMGame.php, test/src/api/responderTest.php, test/tools/api-client/python/lib/test_bmapi.py
Fixes #1640.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/751/
=> Made API always return outOfPlayDieArray

src/engine/BMDie.php, src/engine/BMFlagJustPerformedBerserkAttack.php, src/engine/BMFlagJustPerformedTripAttack.php, src/engine/BMFlagJustPerformedTypeOfAttack.php, src/engine/BMGameAction.php, src/engine/BMSkillBerserk.php, test/src/api/responderTest.php, test/src/engine/BMFlagJustPerformedBerserkAttackTest.php, test/src/engine/BMFlagJustPerformedTypeOfAttackTest.php, test/src/engine/BMGameActionTest.php, test/src/engine/BMSkillBerserkTest.php
Fixes #1620.
This should probably have a responder test added eventually. I tested using spindisc vs spindisc.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/743/
=> Added logic to handle logging of complex size changing that starts with berserk

src/api/DummyApiResponder.php, src/engine/BMInterface.php, src/ui/gui.css, src/ui/js/Api.js, src/ui/js/Overview.js, test/src/ui/js/test_Overview.js, test/tools/api-client/python/lib/test_bmapi.py
Fixes #846.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/732/
=> Hide stale games

src/engine/BMInterface.php, src/ui/js/Api.js, src/ui/js/Game.js, test/src/api/responderTest.php, test/tools/api-client/python/lib/test_bmapi.py
Fixes #784.
This completes the work started in #1222 by Jota.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/736/
=> Only show link to show all logs when some logs are hidden

deploy/vagrant/manifests/init.pp, deploy/vagrant/modules/ntp/manifests/init.pp
* Fixes #1501
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/413/ (assuming it passes)
=> Make sure ntp package is always installed

src/engine/BMSkill.php, src/engine/BMSkillRadioactive.php, test/src/api/responderTest.php, test/src/engine/BMDieTest.php, test/src/engine/BMSkillDoppelgangerTest.php, test/src/engine/BMSkillMorphingTest.php, test/src/engine/BMSkillRadioactiveTest.php
Fixes #1661.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/790/
=> Fixed interaction between rage and radioactive

deploy/jenkins/build.xml, test/src/ui/js/BMTestUtils.js, test/src/ui/js/test_ActivePlayers.js, test/src/ui/js/test_Api.js, test/src/ui/js/test_Buttons.js, test/src/ui/js/test_Forum.js, test/src/ui/js/test_Game.js, test/src/ui/js/test_History.js, test/src/ui/js/test_Login.js, test/src/ui/js/test_Newgame.js, test/src/ui/js/test_Newuser.js, test/src/ui/js/test_OpenGames.js, test/src/ui/js/test_Overview.js, test/src/ui/js/test_Profile.js, test/src/ui/js/test_UserPrefs.js, test/src/ui/js/test_Verify.js
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/792/ (if it passes)
=> Remove unnecessary .empty() JQuery calls from QUnit tests

src/engine/BMSkillDoppelganger.php, src/engine/BMSkillRage.php
Fixes #1674.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/803/ (if it passes)
=> Added interaction between Doppelganger and Rage

src/api/ApiResponder.php, src/engine/BMInterface.php
Continues to address #974, based on comments in #1611.
I was able to create a game of Avis vs Bauer with this new code, so game creation still seems to work.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/813/ (if it passes)
=> Removed need to explicitly instantiate different BMInterface types

src/engine/BMBtnSkillRandomBMMixed.php, test/src/api/responderTest.php, test/src/engine/BMDieTest.php
Continues to address #779.
Depends on pull request #1687.
I have also fixed the unit tests in BMDie that were being skipped because of a dependency on a method that has been recently removed.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/838/
=> Autogenerate description of RandomBMMixed

src/ui/js/Newgame.js
Provides a short-term fix for #1234.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/829/
=> Removed Random Button option for when creating a new game with filters specified

deploy/vagrant/modules/user/manifests/init.pp
Not bothering with jenkins because jenkins doesn't test vagrant module changes.
=> Add Unix account for irilyth

src/engine/BMGame.php, src/engine/BMInterface.php, test/src/api/responderTest.php
Fixes #1489.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/874/
=> Removed fire message overriding

src/ui/js/Forum.js
Fixes #1696.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/857/
=> Switched forum button locations

src/engine/BMAttackSkill.php, src/engine/BMBtnSkillTheJapaneseBeetle.php, test/src/engine/BMAttackSkillTest.php, test/src/engine/BMBtnSkillTheJapaneseBeetleTest.php
Addresses part of #359.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/861/
=> Added logic for The Japanese Beetle

deploy/database/schema.player.sql, deploy/database/updates/1704_fire_overshooting_pref_01.sql, deploy/database/views.game.sql, deploy/database/views.player.sql, src/api/ApiResponder.php, src/api/ApiSpec.php, src/api/DummyApiResponder.php, src/engine/BMGame.php, src/engine/BMInterface.php, src/engine/BMInterfacePlayer.php, src/ui/js/UserPrefs.js, test/src/api/responderTest.php, test/src/engine/BMGameTest.php, test/src/engine/BMInterface000Test.php, test/src/engine/BMInterfacePlayerTest.php, test/src/ui/js/test_Api.js, test/src/ui/js/test_UserPrefs.js
Fixes #1704.
Requires database update 1704_fire_overshooting_pref_01.sql
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/873/
=> Added user preference for fire overshooting

src/ui/js/Forum.js
Fixes #1336.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/869/ (if it passes)
=> Hide "Mark thread as read" when creating thread, and disable it when editing reply

src/ui/js/Game.js
Fixes #1710.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/879/
=> Added attack type to fire turndown message

src/engine/BMInterface.php
Fixes #1722.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/893/
=> Added message for invalid fire turndown

src/engine/BMInterface.php
Fixes #1734. Fixes #1736.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/911/
=> Fixed monitor to only show ACTIVE games

deploy/vagrant/modules/jenkins/templates/config.xml.erb
=> Add jenkins configuration for dwvanstone

src/ui/js/Overview.js
Fixes #1746.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/924/
=> Fixed bug in showing [Accept] for games that someone else has created

src/api/DummyApiResponder.php, src/engine/BMInterface.php, src/ui/js/Api.js, src/ui/js/Overview.js, test/tools/api-client/python/lib/test_bmapi.py
Fixes #1508.
This should show game descriptions for new games, active games, and completed games.
Tested with 1-round haruspex vs haruspex games with descriptions.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/922/
=> Added game description to overview page

src/ui/js/Overview.js
Fixes #1754 
http://jenkins.buttonweavers.com:8080/job/buttonmen-dwvanstone/5/  which will hopefully pass...
=> Change "reject" link to "cancel" link for user who created game.

src/api/ApiResponder.php, src/api/ApiSpec.php, src/api/DummyApiResponder.php, src/engine/BMInterface.php, src/ui/js/Api.js, src/ui/js/Overview.js, src/ui/js/UserPrefs.js, test/src/ui/js/test_Api.js, test/src/ui/js/test_Overview.js
Fixes #1747. Fixes #1758. Fixes #1760. Fixes #1761.
Depends on #1743.
This has been minimally tested for the ability to display rejected games and dismiss rejected games from the list.
It is intentional that rejecting a game does not automatically dismiss it as well.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/928/ (if it passes)
=> Display rejected games in a table

src/ui/js/Game.js, test/src/ui/js/test_Game.js
Addresses part of #1731.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/937/
=> Added basic game pages for pending games

src/ui/js/Overview.js
Fixes #1769.
This change is entirely untested.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/939/ (if it passes)
=> Shifted description column

src/engine/BMAttackSkill.php, src/engine/BMSkill.php, src/engine/BMSkillInsult.php, test/src/api/responderTest.php, test/src/engine/BMAttackSkillTest.php, test/src/engine/BMBtnSkillRandomBMMixedTest.php, test/src/engine/BMSkillInsultTest.php, tools/api-client/python/lib/bmutils.py
Fixes #359.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/929/ (if it passes)
=> Added insult die skill

src/engine/BMSkillTimeAndSpace.php, test/src/api/responderTest.php
Fixes #1804.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/966/
=> Corrected description of TimeAndSpace to account for trip attacks

src/ui/js/Api.js, src/ui/js/Game.js, src/ui/js/Overview.js, test/src/ui/js/test_Overview.js
Fixes #1763. Fixes #1768. Fixes #1782. Fixes #1795.
Dependent on #1811.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/962/
=> Reworked overview page to use only CLOSED and ACTIVE game tables

src/ui/gui.css, src/ui/js/Api.js, src/ui/js/Game.js, src/ui/js/Overview.js, test/src/ui/js/test_Api.js, test/src/ui/js/test_Game.js
=> Added button table for new games

src/ui/js/Env.js
This extracts the mocking code from #1818, since we probably won't be accepting that pull request in its entirety.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/984/
=> Mocked Env.window.confirm()

src/api/ApiSpec.php, src/engine/BMInterface.php, src/ui/js/History.js
Fixes #1770.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/990/
=> Added Rejected / Cancelled to History page

src/engine/BMInterface.php, test/src/api/responderTest.php
Fixes #1757.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/987/
=> Added error message if a game decision becomes invalid

src/ui/js/Game.js, src/ui/js/Overview.js, test/src/ui/js/test_Overview.js
Fixes #1777. Fixes #1767.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/989/
=> Added confirmation messages for Reject Game and Cancel Game links

src/ui/active_players.html, src/ui/buttons.html, src/ui/create_game.html, src/ui/create_user.html, src/ui/forum.html, src/ui/game.html, src/ui/history.html, src/ui/index.html, src/ui/js/Api.js, src/ui/js/Buttons.js, src/ui/js/Forum.js, src/ui/js/Game.js, src/ui/js/Login.js, src/ui/js/Overview.js, src/ui/js/Profile.js, src/ui/open_games.html, src/ui/prefs.html, src/ui/profile.html, src/ui/verify.html, test/src/ui/js/test_Overview.js
Fixes #1806. Fixes #1125. Fixes #1684.
http://jenkins.buttonweavers.com:8080/job/buttonmen-dwvanstone/21/
For #1806:
All page titles have the subpage (or the identifying part of the subpage) in the front of the title. For instance, "Preferences - Button Men Online", For specific buttons, profiles, forum threads, etc.,  the specific name will be in the page title. (e.g., a button page: "Spite - Button Men Online"; a profile page "boilerbrown - Button Men Online")
Note that sometimes the HTML page was changed to have the simple title of "Button Men Online". (Such as buttons.html) In these cases the JS is expected to change the title. I found it less visually jarring to have the title change from "Button Men Online" to "Spite - Button Men Online" than from "Buttons - Button Men Online" to …
=> Made page titles consistent

src/ui/js/Env.js, src/ui/js/Forum.js
Fixes #1177. Fixes #1830. Fixes #1841.
With many thanks to @AdmiralJota for the fix.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1000/ (if it passes)
=> Added forum markup for button, set, wiki, issue

src/ui/js/Game.js
Fixes #1860.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1018/ (if it passes)
=> Fixed bug in Game.showStatePage with an illegal reference to Api

src/engine/BMGame.php, test/src/engine/BMGameTest.php
Fixes #1868.
This is a regression that crept in with pull request #1809.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1019/
=> Fixed regression when using Echo with any other button that has no recipe

src/engine/BMAttack.php, src/engine/BMAttackPower.php, src/engine/BMBtnSkill.php, src/engine/BMButton.php, src/engine/BMDie.php, src/engine/BMGameAction.php, src/engine/BMSkill.php, src/engine/BMSkillMood.php, src/engine/BMSkillTimeAndSpace.php
Continues to address part of #1021.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1021/ (if it passes)
=> Added some missing PHPDoc comments

tools/api-client/python/lib/bmapi.py, tools/api-client/python/lib/bmutils.py
just playing with the api i noticed the API functions `loadNewGames` and `reactToNewGame` were not yet implemented in the python tooling and they were ones i wanted to play with. i went on to also add them to the monitor but in such a specific fashion to my needs i decided not to push up those changes.
let me know if i messed up the target branches or whatever this is my first pull request into you guys 
jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-danlangford/3/ (if it passes)
=> added loadNewGames, reactToNewGame to bmutils, bmapi python clientent tooling

src/engine/BMGame.php
Fixes #1775.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1014/
=> Fixed logic when collating game skills to include all buttons

src/ui/js/Forum.js
* Fixes #1888
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/420/
=> Fix regression by always using the generic entry point to Forum.js

src/ui/help/index.html, src/ui/js/Login.js
Fixes #1892.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1036/ (if it passes)
=> Changed copyright year to 2016

src/ui/help/index.html, src/ui/js/Forum.js, src/ui/js/Login.js
This update brings these approved pulls to the dev branch:
* User-visible:
* #1893: change copyright year to 2016
* Ideally not user-visible: none
Database updates: none
Once this pull is merged, i will load the changes on dev.buttonweavers.com as part of #217.
=> pull changes from master to dev on 2016-01-05

src/ui/js/Forum.js, src/ui/js/Verify.js
This update brings these approved pulls to the dev branch:
* User-visible:
* #1907: fix regression which broke verification of new player accounts
* Ideally not user-visible: none
Database updates: none
Once this pull is merged, i will load the changes on dev.buttonweavers.com as part of #217.
=> pull changes from master to dev on 2016-01-06 (again)

src/engine/BMSkillWeak.php, test/src/api/responderTest.php
Fixes #1884.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1035/
=> Fixed description of weak die skill

src/ui/gui.css
Fixes #1897. 
This is the fix suggested by @AdmiralJota.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1038/
=> Made forum text area larger

src/engine/BMDieOption.php, test/src/api/responderTest.php, test/src/engine/BMDieOptionTest.php
Fixes #1882.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1046/
=> Fixed description of option die with one side

src/engine/BMSkillShadow.php, test/src/api/responderTest.php
Fixes #1930.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1056/
=> Fixed typo in description of Shadow

src/ui/js/Api.js, src/ui/js/Env.js
Fixes #1315.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1050/
=> Changed error message for server connection issues

src/engine/BMGame.php, test/src/api/responderTest.php, test/src/engine/BMGameTest.php
Addresses part of #1289.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1053/
=> Hid swingRequestArray for game states later than SPECIFY_DICE

deploy/database/data.button.sql, deploy/database/updates/01944_zodiac_01.sql
Starts to address part of #1944.
I'll set the sort order once #1943 has been accepted.
Requires database update 01944_zodiac_01.sql
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1078/
=> Added Zodiac set

src/engine/BMGame.php, test/src/api/responderTest.php
Fixes #1883.
Tested bobby vs bobby.
We may need a responder test for this to lock in this behaviour.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1087/
=> Update prevOptValueArray when adding a reserve die

src/ui/js/Api.js
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/430/ (if it passes)
=> Update network error message per tester feedback

deploy/database/schema.game.sql, deploy/database/updates/01991_action_log_end_winner.sql, deploy/database/updates/scripts/01991_migrate_end_winner_action_logs, src/engine/BMGame.php, src/engine/BMGameAction.php, src/engine/BMInterfaceGameAction.php, test/src/api/responderTest.php, test/src/engine/BMGameActionTest.php, test/src/engine/BMGameTest.php
* Related to #1991 
* Fixes #1999 because i had to do so to get Jenkins to pass
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/441/
=> Migrate the end_winner action type's params to an auxiliary table

deploy/database/updates/scripts/01991_migrate_decline_auxiliary_action_logs, src/engine/BMGameAction.php, src/engine/BMInterfaceGame.php, src/engine/BMInterfaceGameAction.php, test/src/engine/BMGameActionTest.php
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/446/ (if it passes)
=> remove unnecessary parameter for "decline_auxiliary" action log type

src/engine/BMBtnSkillRandomBMDuoskill.php, src/engine/BMBtnSkillRandomBMPentaskill.php, src/engine/BMBtnSkillRandomBMTetraskill.php, src/engine/BMBtnSkillRandomBMTriskill.php, test/src/engine/BMBtnSkillRandomBMDuoskillTest.php, test/src/engine/BMBtnSkillRandomBMPentaskillTest.php, test/src/engine/BMBtnSkillRandomBMTetraskillTest.php, test/src/engine/BMBtnSkillRandomBMTriskillTest.php
Addresses initial suggestions in #2007.
Now, each skill should appear exactly twice.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1144/
=> Changed RandomBM*skill so that each skill appears exactly twice

deploy/database/data.button.sql, deploy/database/updates/02006_01_randombm_soldiers.sql, src/engine/BMBtnSkillRandomBMSoldiers.php, test/src/api/responderTest.php, test/src/engine/BMBtnSkillRandomBMSoldiersTest.php
Addresses part of #2006.
http://jenkins.buttonweavers.com:8080/job/buttonmen-irilyth/23/
=> Add RandomBM Soldiers

src/ui/js/Game.js
* Fixes #2012
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/447/ (if it passes)
=> Only override the recipe in END_GAME state

src/engine/BMBtnSkillRandomBM.php, test/src/api/responderTest.php, test/src/engine/BMBtnSkillRandomBMDuoskillTest.php, test/src/engine/BMBtnSkillRandomBMMixedTest.php, test/src/engine/BMBtnSkillRandomBMPentaskillTest.php, test/src/engine/BMBtnSkillRandomBMTetraskillTest.php, test/src/engine/BMBtnSkillRandomBMTriskillTest.php
Addresses part of #2007.
http://jenkins.buttonweavers.com:8080/job/buttonmen-irilyth/25/ (if it passes)
=> Sort skills on RandomBM dice

deploy/database/schema.game.sql, deploy/database/updates/01991_action_log_add_auxiliary.sql, deploy/database/updates/scripts/01991_migrate_add_auxiliary_action_logs, src/engine/BMGameAction.php, src/engine/BMInterfaceGame.php, src/engine/BMInterfaceGameAction.php, test/src/engine/BMGameActionTest.php
* Continues to address #1991 
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/448/ (if it passes)
=> migrate add_auxiliary action log messages to dedicated table

deploy/database/data.button.sql, deploy/database/updates/00779_07_RandomBM.sql
Addresses incomplete database update for #779.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1156/ (if it passes)
=> Updated button flavour texts for RandomBM*Skill

deploy/vagrant/modules/php/manifests/init.pp
=> Pull phpunit from ye 'Old Stable Release' so it's 5.3 compatible.

test/src/api/responderTest.php
This new test demonstrates the behavior described in #2040 and #2041, and also it just generally seems like a good idea to have a Dead Guy regression test on the books.
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/457/ (if it passes)
=> Add a responder test containing Dead Guy

test/src/ui/js/test_OpenGames.js
* Fixes #2049
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/462/ (if it passes)
=> Add enough fake data that unit tests succeed after backend tests are run twice

test/src/ui/js/test_Login.js
* Intended to help with testing #1859 
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/469/
This doesn't bring us to 100% code coverage of Login.js, but i think it hits the majority of the code which defines HTML contents of header and footer elements, so i believe it should be sufficient for getting a handle on what #1859 changes.
=> add tests for Login.js

deploy/database/schema.game.sql, deploy/database/updates/01991_action_log_play_another_turn.sql, deploy/database/updates/scripts/01991_migrate_play_another_turn_action_logs, src/engine/BMInterfaceGameAction.php
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/465/
=> Migrate action logs of type play_another_turn to new format

test/src/engine/BMGameTest.php
* Fixes #2068 
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/473/
=> Use RNG override when testing morphing trip attacks

src/engine/BMAttackTrip.php, test/src/api/responderTest.php
Fixes #2076.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1200/ (if it passes)
=> Fixed trip mighty bug when targeting a konstant die

src/ui/js/Game.js
Fixes #2079.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1202/ (if it passes)
=> Fixed JSDoc comments

src/api/ApiResponder.php, src/api/ApiSpec.php, src/api/api_core.php, src/engine/BMInterfaceGame.php, src/engine/BMInterfaceNewuser.php
Continues to address part of #1130.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1215/
=> Added more PHPDoc comments

src/api/api_core.php
* Fixes #2090 
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/478/ (if it passes)
=> Handle cookies which don't contain stay_logged_in yet

src/api/api_core.php, src/ui/gui.css
This update brings these approved pulls to the dev branch:
* User-visible:
* #2091: fix bug under which site threw an error when people logged in with pre-update cookies
* Ideally not user-visible: none
Database updates: none
Once this pull is merged, i will load the changes on dev.buttonweavers.com as part of #2062.
=> Push changes from master to dev on 2016-07-27

src/engine/BMInterface.php, src/ui/js/Api.js, src/ui/js/Game.js, test/src/api/responderTest.php, test/src/ui/js/test_Game.js, test/tools/api-client/python/lib/test_bmapi.py
Fixes #2094 better than #2095.
I've intentionally created this one on the basis of #2095 so that you have the option of accepting #2095 first and then this one, or just accepting this one (and closing #2095).
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1222/ (if it passes)
=> Die background is now passed as part of the game info, not the player info

src/ui/js/Overview.js, test/src/ui/js/test_Overview.js
Proposed fix for #1955.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1210/
=> testing: Removed word 'Game' from the first column on the overview page

src/engine/BMGame.php, test/src/api/responderTest.php
Proposed fix for #2041.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1227/
=> testing: Stopped unnecessary reroll of zero-valued dice

src/engine/BMGame.php, src/engine/BMSkillPoison.php, test/src/api/responderTest.php, test/src/engine/BMGameTest.php
Proposed fix for #2040, #2008, #1385.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1228/ (if it passes)
=> testing: Added logic to consider poison dice in the calculation of the "can still win" condition

deploy/database/data.button.sql, deploy/database/updates/02032_no_random_dead_guy_01.sql, src/api/ApiResponder.php, src/api/ApiSpec.php, src/engine/BMInterface.php, test/src/api/responderTest.php
Proposed fix for #2032.
In this pull request, I implement generic filtering (both positive and negative) by tag, and then use a negative filter to exclude Dead Guy from random matches.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1231/ (if it passes)
=> testing: Stop Dead Guy from turning up in random matches

src/ui/js/Forum.js
Proposed fix for #2119.
See discussion in http://www.buttonweavers.com/ui/forum.html#!threadId=406
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1235/
=> testing: Added logic to check what sort of click is used on a pseudolink

deploy/database/data.button.sql, deploy/database/updates/02115_cheese_weasel.sql, src/engine/BMBtnSkillCheeseWeasel.php, test/src/engine/BMBtnSkillCheeseWeaselTest.php
Proposed fix for #2115.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1236/
=> testing: Changed Cheese Weasel to having a button special

deploy/vagrant/manifests/init.pp
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/480/ (if it passes)
This code should have no effect on dev.
=> testing: Define puppet_hostname for new IP for staging.buttonweavers.com so its mail will be accepted by more servers

src/ui/js/Overview.js, test/src/ui/js/test_Overview.js
Addresses issue raised in #2084.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1249/
=> testing: Removed hash symbol from overview column header

src/ui/js/Overview.js, test/src/ui/js/test_Overview.js
Fixes #1955.
Testing pull request: #2107.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1210/
=> final: Removed word 'Game' from the first column on the overview page

src/ui/js/Overview.js, test/src/ui/js/test_Overview.js
Fixes issue raised in #2084.
Testing pull request: #2139.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1249/
=> final: Removed hash symbol from overview column header

deploy/vagrant/manifests/init.pp
Testing pull request: #2134.
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/480/ (if it passes)
I intended to load this onto staging as soon as we've verified that it's harmless on dev, so that people can more easily create accounts on staging and receive their verification e-mails.
=> final: Define puppet_hostname for new IP for staging.buttonweavers.com so its mail will be accepted by more servers

src/ui/js/Forum.js
Fixes #2119.
Testing pull request: #2120.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1235/
=> final: Added logic to check what sort of click is used on a pseudolink

deploy/database/data.button.sql, deploy/database/updates/02115_cheese_weasel.sql, src/engine/BMBtnSkillCheeseWeasel.php, test/src/engine/BMBtnSkillCheeseWeaselTest.php
Fixes #2115.
Testing pull request: #2123.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1236/
=> final: Changed Cheese Weasel to having a button special

deploy/vagrant/setup_aws_vagrantfile
http://jenkins.buttonweavers.com:8080/job/buttonmen-irilyth/27/
=> Removed an extraneous .orig from the sed command in setup_aws_vagrantfile.

tools/api-client/python/lib/bmapi.py
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/481/ (if it passes)
I'm submitting a PR for this now because turbo changes the API enough that i need to clean up RandomAI's replay functionality a lot in order to replay-test turbo.  This library represents the major part of RandomAI which is a change to existing code files, rather than being new files.  So i'd like to get it reviewed and accepted to get my workspace in sync with the repo.
As a side effect, obviously if anyone else wants to write a bot in python, this should ideally be helpful to them.
=> Implement all current within-gameplay API methods in the python API client

test/src/api/responderTest.php
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/482/ (if it passes)
* Caused three replay tests which failed without these changes to pass
=> Add some button specials and interactions to responderTest's databank

tools/api-client/python/README.md, tools/api-client/python/lib/random_ai.py, tools/api-client/python/prep_replay_games, tools/api-client/python/replay_loop, tools/api-client/python/test_log_games, tools/api-client/python/update_replay_games
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/484/ (if it passes)
* Other testing done: i've been using this stuff to do replay testing of turbo (with modifications to support turbo, not included).  In addition, i did a smoke test on a virtualbox vagrant instance on this branch using something like:
```
scp example_players.sql vagrant:
mkdir -p share/buttonmen/
scp share/buttonmen/.bmrc vagrant:share/buttonmen/
cp /buttonmen/tools/api-client/python/replay_loop ~
sudo mkdir -p /srv/bmgames/chaos-test/{replay_state,archive}
sudo chown chaos /srv/bmgames/chaos-test/{replay_state,archive}
mkdir -p src/buttonmen/{lib,output}
cp /buttonmen/tools/api-client/python/test_log_games ~/src/buttonmen/
cp /buttonmen/tools/api-client/python/prep_replay_games ~/src/buttonmen/
cp …
```
=> Initial commit of random_ai.py and related replay scripts

test/src/api/responderTest.php
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/486/
=> Added all remaining known button specials and skill interactions to responderTest

tools/api-client/python/head-to-head
http://jenkins.buttonweavers.com:8080/job/buttonmen-irilyth/31/
=> Added a script for calculating head-to-head win percentages

tools/api-client/python/record
http://jenkins.buttonweavers.com:8080/job/buttonmen-irilyth/30/
=> Added a script for calculating overall records

tools/api-client/python/lib/random_ai.py
These are the changes i needed to make to random_ai.py to support Turbo's changes to the API
* Testing done: used this code to test against #2152.  (Jenkins doesn't currently do any testing involving random_ai.py, though i can run it if you prefer.)
=> Add RandomAI support for Turbo API changes

src/ui/js/Login.js, test/src/ui/js/test_Login.js
Addresses #2169 in the easiest way, but doesn't fix it in perpetuity.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1297/ (if it passes)
=> Updated copyright year to 2017

src/ui/gui.css, src/ui/js/Game.js, test/src/ui/js/test_Game.js
Addresses part of #2175.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1300/ (if it passes)
=> Make turbo selector always visible

src/ui/js/Overview.js
This is a pull request containing the rest of the stuff that Jota noted on #2136.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1299/
=> Fixed link to Button Men site

src/ui/gui.css, src/ui/js/Game.js, test/src/ui/js/test_Game.js
Fixes #2172.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1298/ (if it passes)
=> Make swing input field trigger number pad on touch devices

tools/api-client/python/lib/bmapi.py, tools/api-client/python/lib/bmutils.py
http://jenkins.buttonweavers.com:8080/job/buttonmen-irilyth/39/ (if it passes)
=> Updated bmapi.py and bmutils.py to allow you to specify player (the first player) and description

tools/api-client/python/game-create, tools/api-client/python/game-data
http://jenkins.buttonweavers.com:8080/job/buttonmen-irilyth/43/ (if it passes)
=> Added new scripts game-create and game-data for creating and getting data about games

src/ui/active_players.html, src/ui/buttons.html, src/ui/create_game.html, src/ui/create_user.html, src/ui/forum.html, src/ui/game.html, src/ui/history.html, src/ui/index.html, src/ui/js/Loader.js, src/ui/open_games.html, src/ui/prefs.html, src/ui/profile.html, src/ui/verify.html
Fixes #2220.
This may require people to do a hard reload of various browser pages if we change the underlying JS.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1346/ (if it passes)
=> Force JS script files to cache

tools/api-client/python/buttons-with-skills
http://jenkins.buttonweavers.com:8080/job/buttonmen-irilyth/51/ (if it passes)
=> Added new script buttons-with-skills for getting a list of the buttons with a set of skills

tools/api-client/python/lib/random_ai.py
* Partially addresses #2233 (see later comments for weird behavior which may be server-side and is not yet diagnosed)
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/495/ (if it passes)
=> Have random_ai invoke create_game() correctly given that it uses keyword args

src/engine/BMGame.php, test/src/api/responderTest.php
Fixes #2041.
testing pull: #2106
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1208/
=> Stopped unnecessary reroll of zero-valued dice

deploy/amp/phpunit_bootstrap.php, deploy/jenkins/phpunit_bootstrap.php, deploy/vagrant/modules/buttonmen/templates/phpunit.php.erb, src/engine/BMBtnSkillRandomBM.php, src/lib/bootstrap.php, test/src/api/responderTest.php, test/src/engine/BMBtnSkillRandomBMDuoskillTest.php, test/src/engine/BMBtnSkillRandomBMFixedTest.php, test/src/engine/BMBtnSkillRandomBMMixedTest.php, test/src/engine/BMBtnSkillRandomBMMonoskillTest.php, test/src/engine/BMBtnSkillRandomBMPentaskillTest.php, test/src/engine/BMBtnSkillRandomBMTest.php, test/src/engine/BMBtnSkillRandomBMTetraskillTest.php, test/src/engine/BMBtnSkillRandomBMTriskillTest.php, tools/api-client/python/lib/bmapi.py, tools/api-client/python/lib/random_ai.py, tools/api-client/python/replay_loop
* Unblock regression testing for #2210 
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/500/ (if it passes)
=> Modify bm_rand() handling to use a separate function for skill-selection random numbers

tools/stats/R/calcStats.R
Addresses part of #614.
So, I thought that it might be a good idea for me to submit the current version of my stats script to the repository, firstly so it doesn't get lost, and secondly so that we can start moving forward on getting stats working on the live site.
I don't anticipate any problems with Jenkins since I'm only submitting one file to the tools directory, but here it is anyway:
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1360/ (if it passes)
=> Initial check-in of stats script

src/ui/js/Buttons.js
Fixes #2190.
This is @AdmiralJota's proposed fix, taken directly from the gist provided.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1352/ (if it passes)
=> Added button history links

tools/api-client/python/replay_loop
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/504/ (if it passes, which it should, since jenkins doesn't use replay_loop)
=> Fix replay_loop regression

src/ui/js/Overview.js, test/src/ui/js/test_Overview.js
@AdmiralJota's solution that fixes #1119.
When #1821 has been accepted, this pull request will probably need to be deconflicted.
I am currently unsure whether the count of closed games is really necessary for consistency, since I don't think the number would every be really meaningful.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1001/ (if it passes)
=> Added number of active games to overview

deploy/database/schema.game.sql, deploy/database/updates/01784_game_creation_action_log.sql, src/engine/BMGameAction.php, src/engine/BMInterface.php, src/engine/BMInterfaceGame.php, src/engine/BMInterfaceGameAction.php, test/src/api/responderTest.php, test/src/engine/BMGameActionTest.php, test/src/ui/js/test_Game.js
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/507/ (if it passes)
* Relevant to #1784
=> Add an action_log entry at game creation time

deploy/database/data.button.sql, deploy/database/updates/02032_no_random_dead_guy_01.sql, src/api/ApiResponder.php, src/api/ApiSpec.php, src/engine/BMInterface.php, src/engine/BMPlayer.php, test/src/api/responderTest.php
Fixes #2032.
Testing pull requests: #2110, #2137.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1255/
=> Stop Dead Guy from turning up in random matches

src/ui/gui.css, src/ui/js/Newgame.js, test/src/ui/js/test_Newgame.js
Addresses part of #1784.
With this change, it is possible for anyone to create a third-party game from the standard create game page.
@cgolubi1, I haven't added any UI testing of this to the QUnit tests. I'd like some guidance on what sort of test you'd like here.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1369/
=> Added UI changes for third-party game creation

deploy/vagrant/manifests/init.pp, deploy/vagrant/modules/buttonmen/manifests/init.pp, deploy/vagrant/modules/buttonmen/templates/setup_ui_cache_links.erb, src/ui/active_players.html, src/ui/buttons.html, src/ui/create_game.html, src/ui/create_user.html, src/ui/forum.html, src/ui/game.html, src/ui/history.html, src/ui/index.html, src/ui/open_games.html, src/ui/prefs.html, src/ui/profile.html, src/ui/verify.html
* Fixes #2255 
* Fixes #772
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/509/
=> Simple symlink autoversioning for BM JS and CSS files

src/ui/js/Game.js, test/src/ui/js/test_Game.js
* Fixes #464 
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/505/ (if it passes)
=> UI for setting chat privacy within a game

src/engine/BMSkillBerserk.php, src/engine/BMSkillTurbo.php, test/src/api/responderTest.php
Fixes #2239.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1380/
=> Added description of berserk/turbo interaction

src/engine/BMInterface.php, src/engine/BMInterfaceGame.php
Fixes #1130.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1392/ (if it passes)
=> Addressed remaining PHPDoc warnings

src/ui/js/Game.js
Fixes #1709.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1412/
=> Changed wording of dropdown select text for cancelling during fire turndown

src/ui/js/Env.js
Fixes #2298.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1427/ (if it passes)
=> History page now shows dash for unspecified buttons

src/engine/BMGameAction.php, test/src/api/responderTest.php
Fixes #2217.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1386/ (if it passes)
=> Removed 'changed size due to turbo' message

src/engine/BMSkillMood.php, src/engine/BMSkillRadioactive.php, src/engine/BMSkillTimeAndSpace.php, src/engine/BMSkillTurbo.php, test/src/api/responderTest.php
Fixes #1794.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1389/
=> Added interaction descriptions for skills that are lost during radioactive decay

src/engine/BMSkillKonstant.php, src/engine/BMSkillTimeAndSpace.php, test/src/api/responderTest.php
Fixes #1962.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1384/ (if it passes)
=> Added description of interaction between Konstant and TimeAndSpace

tools/api-client/python/lib/random_ai.py
Add RandomAI support for #2279 
No jenkins run because jenkins doesn't use random_ai.py
I'm testing this on a replay site with the code in #2279 --- shadowshade, can you approve my merging it at the same time as i merge that pull?
=> Add RandomAI support for Gordo and Guillermo

tools/api-client/python/lib/random_ai.py
* Needed for regression testing of #2279
* No jenkins because the only change is to randomAI
=> Finish RandomAI support for Gordo by supporting mandatory auxiliary die decline

src/api/ApiResponder.php, src/api/ApiSpec.php, src/api/DummyApiResponder.php, src/engine/BMInterfaceGame.php, src/ui/js/Api.js, src/ui/js/Game.js, src/ui/js/OpenGames.js, test/src/api/responderTest.php, test/src/engine/BMInterfaceGameTest.php, test/src/ui/js/test_Api.js, test/src/ui/js/test_OpenGames.js
Fixes #1733.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1408/
=> Added ability to cancel open games

test/src/api/responderTest.php
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/518/
=> Add description of Gordo button skill to responderTest

src/engine/BMAttackTrip.php, test/src/api/responderTest.php
Fixes #2289.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1410/
=> Fixed bug with weak dice tripping twin dice

test/src/api/responderTest.php
* Should fix the occasional entirely-unsurprising replay test failures i've been getting against master
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/519/ (if it passes)
=> Add Guillermo skill description to responder test

tools/api-client/python/lib/random_ai.py
* Used for testing #2210
* Should be a noop until Rush is merged (and random_ai doesn't have unit tests)
=> Add Rush support to RandomAI

src/engine/BMAttack.php, src/engine/BMAttackDefault.php, src/engine/BMAttackRush.php, src/engine/BMAttackSpeed.php, src/engine/BMSkill.php, src/engine/BMSkillRush.php, test/src/api/responderTest.php, test/src/engine/BMAttackRushTest.php, test/src/engine/BMAttackTest.php, test/src/engine/BMBtnSkillRandomBMMixedTest.php, test/src/engine/BMSkillRushTest.php, test/src/engine/BMSkillTest.php, tools/api-client/python/lib/bmutils.py
Fixes #2176.
This pull request implements the version of Rush most recently proposed by James Ernest.
This requires a responder test to lock in the behaviour of Rush dice.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1333/
=> Added Rush skill, take 3

src/ui/js/Login.js, test/src/ui/js/test_Login.js
This is the yearly update to the copyright year, similar to #2177.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1470/ (if it passes)
=> Updated copyright year to 2018

.circleci/config.yml, deploy/circleci/manifests/init.pp, deploy/jenkins/audit_js_unit_test_coverage.py, deploy/jenkins/checkstyle/buttonmen.xml, deploy/jenkins/pmd/buttonmen.xml, deploy/vagrant/manifests/init.pp, deploy/vagrant/modules/apache/manifests/init.pp, deploy/vagrant/modules/buttonmen/manifests/init.pp, deploy/vagrant/modules/javascript/manifests/init.pp, deploy/vagrant/modules/javascript/templates/run-jscover-qunit.js.erb, deploy/vagrant/modules/php/manifests/init.pp, src/api/ApiResponder.php, src/api/ApiSpec.php, src/api/DummyApiResponder.php, src/api/api_core.php, src/engine/BMDie.php, src/engine/BMDieSwing.php, src/engine/BMGame.php, src/engine/BMGameAction.php, src/engine/BMInterface.php, src/engine/BMInterfaceGameAction.php, src/engine/BMInterfaceGameChat.php, src/engine/BMInterfaceHistory.php, src/engine/BMInterfaceNewuser.php, src/engine/BMInterfacePlayer.php, src/engine/BMUtilityHitTable.php, src/engine/BMUtilityXCYIterator.php, src/ui/js/Env.js, test/src/ui/phantom-index.html, test/tools/api-client/python/lib/test_bmapi.py
* CircleCI: https://circleci.com/gh/cgolubi1/buttonmen/60
I think this is a working CircleCI configuration that has enough of the core functionality that we can adopt it and move forward, unblocking development work.  The only arguably important thing that's missing is JS code coverage, which i'd like to have, but which will take some thinking to get working on a new site, and it doesn't strike me as worth holding up the world over.
=> Add an initial v2.0 circleci config

deploy/database/data.button.sql, deploy/database/updates/02333_reenable_oregon_01.sql, src/engine/BMBtnSkillOregon.php, test/src/engine/BMBtnSkillOregonTest.php, tools/api-client/python/lib/random_ai.py
=> Re-enabled Oregon

src/engine/BMAttackSkill.php, src/engine/BMCanHaveSkill.php, test/src/api/responderTest.php, test/src/engine/BMCanHaveSkillTest.php
=> Fixed bug with skill attack containing more than two zero-sided dice

src/engine/BMInterfaceGame.php, test/src/api/responderTest.php
=> Fixed spurious turbo-fire-radioactive internal error

src/ui/tools/table_converter.html
Fixes #2356.
So, I'm just adding Jota's HTML/JQuery page that converts tables from Excel into a [code] block that can be posted into our forums.
I figure that other external tools (like Bagel's button filter) might also fit into the /external folder.
=> Added Jota's page that converts XLS-pasted tables into forum tables

test/src/api/responderTest.php
* Assuming it passes, should fix a couple of replay test errors i found in my default replay loop
=> Add Oregon to responderTest's skill descriptions

src/engine/BMSkillChance.php, src/engine/BMSkillMighty.php, src/engine/BMSkillWeak.php, test/src/api/responderTest.php
Fixes #1966.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1383/ (if it passes)
=> Added description of interaction between mighty/weak and chance

deploy/database/data.button.sql, deploy/database/updates/02333_reenable_oregon_02.sql
=> Enable btn_special for Oregon in database

deploy/database/data.button.sql, deploy/database/updates/02378_brigid_description_01.sql
=> Fixed typo in Brigid's flavour text

src/engine/BMSkillMorphing.php, test/src/api/responder03Test.php, test/src/api/responderTestFramework.php
Fixes #1956.
There's no responder test for this yet, and it's probably a good idea to have one.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1471/ (if it passes)
=> Changed morphing skill so that it does not trigger when there are multiple defending dice

tools/api-client/python/lib/random_ai.py, tools/api-client/python/replay_loop
* Fixes #2386 
* I tested this on AWS in the usual way, and it successfully played and cached a number of games with no failures
=> Update replay_loop to work with new responderTest format

src/api/api_core.php, src/engine/BMAttack.php, src/engine/BMAttackDefault.php, src/engine/BMAttackSkill.php
Just resolving some small missing comments noted in the PHPDoc output.
=> Added missing PHPDoc comments

src/engine/BMDie.php, src/engine/BMFlagIsAboutToPerformTripAttack.php, src/engine/BMGame.php, src/engine/BMSkillTimeAndSpace.php, src/engine/BMSkillTrip.php, test/src/api/responder03Test.php, test/src/engine/BMFlagIsAboutToPerformTripAttackTest.php, test/src/engine/BMGameTest.php, test/src/engine/BMSkillTimeAndSpaceTest.php
Addresses #2253.
So, I'm putting this incomplete pull request up as a place to get all our comments in the one place.
=> Interaction between Turbo and TimeAndSpace

tools/api-client/python/create_game, tools/api-client/python/game_info, tools/api-client/python/head-to-head, tools/api-client/python/interactive_mode.py, tools/api-client/python/lib/bmapi.py, tools/api-client/python/lib/bmutils.py, tools/api-client/python/monitor, tools/api-client/python/record
http://jenkins.buttonweavers.com:8080/job/buttonmen-irilyth/38/ (if it passes)
Addresses much of #2197.
I've tested a bunch of this stuff by running it with 'python2' and 'python3' on my Ubuntu 12.04 box, which has Python 2.7.3 and Python 3.2.3.
I didn't touch prep_replay_games, replay_loop, test_log_games, or update_replay_games, because I wasn't sure how to test them safely.
=> Added a bunch of stuff to make a bunch of things Python 3 compatible

src/engine/BMAttackTrip.php, test/src/engine/BMAttackTripTest.php
=> Account for postroll maximum of mood/mad dice better

src/engine/BMAttackDefault.php
Fixes #1721.
Testing pull request: #2111.
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1232/ (if it passes)
=> Fixed default attack when fire overshooting is off

src/ui/js/Game.js
Fixes #2296.
This is the new improved (and much simplified!) version of #2324.
=> Cache chat across toggle of chat visibility

tools/api-client/python/lib/bmutils.py
* Addresses what i think is the root of the merge problem giving us trouble in #2403
=> Keep trying to fix wrapper error by printing the message rather than the object

.circleci/config.yml, deploy/circleci/manifests/init.pp, deploy/vagrant/Vagrantfile, deploy/vagrant/manifests/init.pp, deploy/vagrant/modules/apache/manifests/init.pp, deploy/vagrant/modules/apache/templates/site_default.erb, deploy/vagrant/modules/apt/manifests/init.pp, deploy/vagrant/modules/apt/templates/10periodic.erb, deploy/vagrant/modules/buttonmen/manifests/init.pp, deploy/vagrant/modules/buttonmen/templates/phpunit.php.erb, deploy/vagrant/modules/buttonmen/templates/run_buttonmen_tests.erb, deploy/vagrant/modules/javascript/manifests/init.pp, deploy/vagrant/modules/javascript/templates/install_phantomjs.erb, deploy/vagrant/modules/mysql/manifests/init.pp, deploy/vagrant/modules/mysql/templates/buttonmen.cnf.erb, deploy/vagrant/modules/php/manifests/init.pp, src/engine/BMInterfaceGame.php, test/src/engine/BMGameTest.php, test/src/engine/BMInterfaceGameTest.php, test/src/engine/BMInterfaceTest.php, tools/api-client/python/lib/bmutils.py, tools/api-client/python/replay_loop, tools/api-client/python/replay_single_game, util/grunt/circleci-grunt.sh
* User-visible: none
* Ideally not user-visible:
* #2413: upgrade site to Ubuntu Xenial
```
UPDATES=""
SCRIPTS=""
```
Once this pull is merged, i will load the changes on staging.buttonweavers.com as part of #2407.
=> Push changes from master to staging on 2018-11-14

.circleci/config.yml, deploy/circleci/manifests/init.pp, deploy/vagrant/Vagrantfile, deploy/vagrant/manifests/init.pp, deploy/vagrant/modules/apache/manifests/init.pp, deploy/vagrant/modules/apache/templates/site_default.erb, deploy/vagrant/modules/apt/manifests/init.pp, deploy/vagrant/modules/apt/templates/10periodic.erb, deploy/vagrant/modules/buttonmen/manifests/init.pp, deploy/vagrant/modules/buttonmen/templates/phpunit.php.erb, deploy/vagrant/modules/buttonmen/templates/run_buttonmen_tests.erb, deploy/vagrant/modules/javascript/manifests/init.pp, deploy/vagrant/modules/javascript/templates/install_phantomjs.erb, deploy/vagrant/modules/mysql/manifests/init.pp, deploy/vagrant/modules/mysql/templates/buttonmen.cnf.erb, deploy/vagrant/modules/php/manifests/init.pp, src/engine/BMInterfaceGame.php, test/src/engine/BMGameTest.php, test/src/engine/BMInterfaceGameTest.php, test/src/engine/BMInterfaceTest.php, tools/api-client/python/lib/bmapi.py, tools/api-client/python/lib/bmutils.py, tools/api-client/python/replay_loop, tools/api-client/python/replay_single_game, util/grunt/circleci-grunt.sh
This update brings these approved pulls to the production branch:
* User-visible: none
* Ideally not user-visible:
* #2413: upgrade site to Ubuntu Xenial
```
UPDATES=""
SCRIPTS=""
```
Master issue for this release: #2407
master issue for all pushes to prod: #700
=> Push changes from staging to production on 2018-11-16

src/engine/BMInterfacePlayer.php, test/src/api/responder00Test.php
=> Fix PHP7 password hash bug

test/src/api/responder00Test.php
* Relevant to #2419 
* CircleCI run is https://circleci.com/gh/cgolubi1/buttonmen/178 - not sure why github didn't pick it up
=> Change the password to the same value in responder test

src/ui/js/Login.js, test/src/ui/js/test_Login.js
=> Changed copyright year to 2019

src/api/ApiSpec.php, src/api/dummy_responder.php, src/api/responder.php, src/ui/js/Api.js, src/ui/js/Login.js, test/src/api/responder00Test.php, tools/api-client/python/lib/bmapi.py
* Prerequisite for #1209
* This change modifies the format of ALL API posts, so it is a breaking change for clients, but the required changes should be very simple
* No API method syntax is changing, but the purpose of this commit is to unblock future work by allowing us to pass args more cleanly than urlencoding would allow
=> JSON serialize API input for submission

.circleci/config.yml, deploy/vagrant/modules/php/manifests/init.pp
=> Install phpcs from github rather than from pear.php.net

tools/stats/R/calcStats.R
This should be unproblematic because it only touches the R script that I use to generate stats.
=> Updated stats script to generate player vs player stats

tools/api-client/python/lib/random_ai.py
This lets RandomAI continue to work after the merge of #2423
=> RandomAI support for Jolt

src/engine/BMSkillJolt.php, test/src/api/responderTestFramework.php
=> Make skill interaction text between Jolt and TimeAndSpace identical between both uses

deploy/database/data.button.sql, deploy/database/updates/02446_flavour_01.sql
Fixes #2440. Fixes #2446.
New flavour text for Vysion (written by Vysion himself), and filling in missing flavour text for the Geekz button set.
=> Added flavour text for Vysion and the Geekz button set

deploy/vagrant/modules/php/manifests/init.pp
=> Get pdepend from apt rather than from pear

src/ui/about.html, src/ui/faq.html, src/ui/getting-started.html, src/ui/gui.css, src/ui/help.html, src/ui/js/About.js, src/ui/js/Faq.js, src/ui/js/GettingStarted.js, src/ui/js/Help.js, src/ui/js/Login.js, src/ui/js/Skills.js, src/ui/skills.html, test/src/ui/index.html, test/src/ui/js/test_About.js, test/src/ui/js/test_Faq.js, test/src/ui/js/test_GettingStarted.js, test/src/ui/js/test_Help.js, test/src/ui/js/test_Login.js, test/src/ui/js/test_Skills.js, test/src/ui/phantom-index.html
This starts to address part of #137.
Currently, the pull request is incomplete, and I'd like input (and help) before I push this through to completion. I'll attach a screenshot as the first response so that it's easier for people to start commenting.
@cgolubi1, is this going in roughly the right direction, and what sort of testing should we be doing here? @AdmiralJota, how would you make this look nicer? Everyone, what do you think about the text (which comes directly from #1149)?
Of course, there is also text there that will probably be commented out (because the pages don't already exist). I'm happy to also accept comments about obvious stuff like that.  :)
=> Adding a help link

deploy/database/data.button.sql, deploy/database/updates/02360_peloton_final_02.sql
Fixes issue found in #2472 by replacing non-ASCII characters
=> Changed ellipsis to three dots to make flavour text ASCII-only

deploy/database/data.player.sql, deploy/database/schema.player.sql, deploy/database/updates/00141_password_reset.sql, src/api/ApiResponder.php, src/api/ApiSpec.php, src/api/DummyApiResponder.php, src/engine/BMEmail.php, src/engine/BMInterfaceNewuser.php, src/ui/forgot_password.html, src/ui/js/ForgotPassword.js, src/ui/js/Login.js, src/ui/js/VerifyReset.js, src/ui/verify_reset.html, test/src/api/responder00Test.php, test/src/ui/index.html, test/src/ui/js/test_ForgotPassword.js, test/src/ui/js/test_Login.js, test/src/ui/js/test_VerifyReset.js, test/src/ui/phantom-index.html
=> Add password reset interface and API

src/ui/js/Login.js, test/src/ui/js/test_Login.js
=> Updated copyright year to 2020

src/engine/BMInterfaceNewuser.php, test/src/api/responder00Test.php
=> Delete password reset verification key after it is used

deploy/circleci/manifests/init.pp, deploy/database/README.RDS_MIGRATION, deploy/vagrant/manifests/init.pp, deploy/vagrant/modules/apache/templates/site_default.erb, deploy/vagrant/modules/buttonmen/manifests/init.pp, deploy/vagrant/modules/buttonmen/templates/apache.conf.erb, deploy/vagrant/modules/buttonmen/templates/backup_database.erb, deploy/vagrant/modules/buttonmen/templates/create_rds_database.erb, deploy/vagrant/modules/buttonmen/templates/mysql_root_cli.erb, deploy/vagrant/modules/mysql/manifests/init.pp
* Fixes #2523 
DO NOT MERGE THIS - it needs to be rebased, and i need to actually create the staging and production databases and put their FQDNs in.  I'm putting it up for review to make sure the approach looks fine.
=> add support for a remote (RDS) buttonmen database

src/ui/js/Help.js
=> Update help text for password reset

src/ui/gui.css, src/ui/js/Faq.js, test/src/ui/js/test_Faq.js
=> Added FAQ text

tools/stats/R/calcStats.R
This pull request just caches the changes needed for coloured stats pages.
=> Added option to create coloured stats pages

src/ui/js/Login.js, src/ui/js/Privacy.js, src/ui/privacy.html, test/src/ui/index.html, test/src/ui/js/test_Login.js, test/src/ui/js/test_Privacy.js, test/src/ui/phantom-index.html
Fixes #551.
The wording of the privacy policy is still up for debate, if anyone wants anything changed.
=> Added privacy policy

src/ui/gui.css, src/ui/js/Buttons.js
=> Added tournament legal status to button page

src/ui/js/OpenGames.js
=> Changed Open Games page to show your open games first

src/ui/gui.css, src/ui/js/Env.js, test/src/ui/js/test_Env.js
=> Made anchors that are in hidden spoilers unclickable

src/ui/js/Game.js
This pull request fixes a number of missing semicolons that were incorrectly commas in Game.js.
=> Fixed missing semicolons

deploy/vagrant/manifests/init.pp, deploy/vagrant/modules/cloudwatch/manifests/init.pp, deploy/vagrant/modules/cloudwatch/templates/record_buttonmen_metrics.erb
* User-visible: none
* Ideally not user-visible:
* #2596: fix cloudwatch metrics reporting script
```
UPDATES=""
SCRIPTS=""
```
Once this pull is merged, i will load the changes on staging.buttonweavers.com as part of #2577.
=> Push changes from master to staging on 2020-08-16

src/ui/js/Profile.js
=> Added explanatory suffix to self-challenge solipsism when viewing your own profile

src/ui/js/Game.js
=> Added button name to compact mode

deploy/database/data.button.sql, deploy/database/updates/02488_largo_01.sql, src/engine/BMBtnSkillLargo.php, test/src/api/responderTestFramework.php, test/src/engine/BMBtnSkillLargoTest.php
=> Made Largo playable, and fixed recipe

src/engine/BMGame.php, test/src/engine/BMGameTest.php
=> Fixed bug with boom twin dice

src/api/ApiResponder.php, src/api/ApiSpec.php, src/api/DummyApiResponder.php, src/engine/BMDieOption.php, src/engine/BMDieSwing.php, src/engine/BMDieTwin.php, src/engine/BMInterface.php, src/engine/BMInterfaceHelp.php, src/engine/BMInterfaceNewuser.php, src/engine/BMSkill.php, src/ui/gui.css, src/ui/js/Api.js, src/ui/js/Skills.js, test/src/api/responder00Test.php, test/src/api/responderTestFramework.php, test/src/engine/BMInterfaceHelpTest.php, test/src/ui/js/BMTestUtils.js, test/src/ui/js/test_Skills.js
Fixes #1925.
This builds on the code of @AdmiralJota and the tweaks by @dwvanstone.
=> Added skills description page

src/engine/BMCanHaveSkill.php, test/src/api/responder03Test.php, test/src/engine/BMGameTest.php
=> Propagate twin die die hooks to subdice

src/engine/BMInterfaceGame.php, src/ui/js/Api.js, src/ui/js/Game.js
Fixes #2332.
I know that @irilyth will be especially pleased about this functionality.
=> Added functionality to cancel third-party games if you are the creator

tools/stats/R/calcStats.R
I'm just getting these changes to the stats script out of my working directory and into the repository, since they're what I'm using at the moment, and I'm getting sick of continually stashing them.
=> Updated stats script

src/engine/BMDie.php, src/engine/BMGameAction.php, test/src/api/responder01Test.php, test/src/api/responder03Test.php, test/src/engine/BMGameActionTest.php
Fixes #1411.
This pull request is the first (major) part of #2629, and does not resolve the problem reported in #1663.
=> Added logging logic for mood recipe changes, part 2a

src/ui/gui.css, src/ui/js/About.js, src/ui/js/Help.js
Fixes #2468.
I've also taken this opportunity to add a link from the main help page to the Button Men wiki.
=> Added text to About page

deploy/database/data.button.sql, deploy/database/updates/02627_zoecon_flavour_text_01.sql
=> Added flavour text for ZOECon buttons

src/api/ApiSpec.php
* Partially addresses #712
* Relevant to #2641
=> Sanitize subarray values

src/ui/js/Newgame.js
=> Made opponent name persistent when changing first player

src/engine/BMInterfaceGame.php, src/engine/BMInterfacePlayer.php
Fixes #1294.
I've been through all the functions in BMInterface*.php and added try/catch blocks to those functions that are not already covered by a try/catch block.
=> Added try/catch blocks to BMInterface functions

src/engine/BMAttackShadow.php
=> Made BMAttackShadow->validate_attack() function declaration consistent

LICENSE.txt, README.md
I noticed that our LICENSE and README files were out of date, so I decided to update them.
=> Updated license and readme

src/ui/js/ForgotPassword.js
Fixes buttonmen-dev/buttonmen#2662 by simply trimming the input in JS
edit: s/addressing/Fixes/
=> trimming username input

src/api/ApiResponder.php
=> Added check for whether verify_function_args receives an array

src/engine/BMInterfaceGameChat.php
=> Changed warning message when not changing an empty chat message

tools/api-client/python/lib/bmapi.py, tools/api-client/python/lib/bmutils.py
i needed this functionality and thought i could give it back to the community
=> add some New Game functionality to the python api-client

deploy/circleci/audit_php_files.php, src/engine/BMInterfaceForum.php
=> Migrate BMInterfaceForum to BMDB

LICENSE.txt, src/ui/js/Login.js, test/src/ui/js/test_Login.js
=> Updated copyright year to 2021

src/engine/BMSkillKonstant.php, src/engine/BMSkillTurbo.php, src/engine/BMSkillWarrior.php, test/src/api/responderTestFramework.php
=> Added interaction text for Warrior Turbo and Warrior Konstant

util/grunt/npm_install_grunt
=> Use an older version of grunt-cli to avoid micromatch version issue

deploy/vagrant/modules/fqdn/templates/from_ec2_tags.erb
=> Use reliably-available ec2_placement_availability_zone to determine region for FQDN tag query

deploy/circleci/audit_php_files.php, src/engine/BMDB.php, src/engine/BMInterfaceGameAction.php
=> Convert BMInterfaceGameAction to use BMDB instead of direct database actions

tools/api-client/python/lib/random_ai.py
=> Make CustomBM actually work under RandomAI replay loops

src/engine/BMInterfaceGame.php
* User-visible:
* #2763
* Ideally not user-visible: none
Database updates: none
Once this pull is merged, i will load the changes on staging.buttonweavers.com as part of #2733.
=> Push changes from master to staging on 2021-09-12

deploy/vagrant/modules/buttonmen/manifests/init.pp, deploy/vagrant/modules/buttonmen/templates/test_config.erb
There's not an issue for this, but i'm tired of getting bitten by it.
=> Add a cron job to test whether the database site_type matches the javascript site_type

deploy/circleci/audit_php_files.php, src/engine/BMInterface.php
=> Migrate BMInterface.php to BMDB

deploy/circleci/audit_php_files.php, src/engine/BMInterfaceGame.php
=> Migrate BMInterfaceGame.php to BMDB

src/engine/BMInterface.php, test/src/engine/BMInterfaceTest.php
=> Fix get_friendly_time_span regression

deploy/vagrant/manifests/init.pp, deploy/vagrant/modules/mysql/manifests/init.pp
* Also cleanup the current IP of the RDS dev site so it can be used for testing
=> Uninstall mysql-server, rather than installing it, on RDS sites

deploy/vagrant/manifests/init.pp, deploy/vagrant/modules/mysql/manifests/init.pp
* #2792
```
UPDATES=
SCRIPTS=
```
=> Push changes from master to staging on 2021-12-29

src/engine/BMInterface.php
=> Reversed order of open games

src/ui/help/index.html, src/ui/js/Login.js, src/ui/js/Overview.js, test/src/ui/js/test_Login.js
fix some broken links
resolves buttonmen-dev/buttonmen#2781.
i want to see if `test_Login.js` fails
=> fix broken links

deploy/database/data.button.sql, deploy/database/updates/02810_hide_custombm_01.sql, test/src/api/responder00Test.php
=> Added btn_special flag to CustomBM to hide it from the live site

tools/api-client/python/lib/random_ai.py
=> RandomAI should fail on obviously-buggy game creation failures

src/ui/js/Login.js
=> Fix appearance of links in footer to match actual underlying link

src/ui/js/Login.js
Reverts buttonmen-dev/buttonmen#2817
=> Revert "Fix appearance of links in footer to match actual underlying link"

src/ui/js/Login.js, test/src/ui/js/test_Login.js
=> Fix appearance of links in footer to match actual underlying link, take 2

src/engine/BMAttackTrip.php, test/src/engine/BMAttackTripTest.php
=> Correct calculation of trip attack validity vs Maximum Mood

src/engine/BMInterfaceGame.php, src/ui/js/Newgame.js, test/src/api/responder00Test.php
Fixes #2839.
I guess we'll either need a trial 'staging' site or we trust that this is correct and test it when we roll out to 'staging' as normal.
=> Enable CustomBM on staging

deploy/vagrant/modules/buttonmen/templates/backup_database.erb
* Fixes #2808 (as far as i know)
=> Use the --single-transaction flag to make backups less disruptive

LICENSE.txt, src/ui/js/Login.js, test/src/ui/js/test_Login.js
=> Changed copyright dates to 2022

deploy/vagrant/Vagrantfile, deploy/vagrant/setup_aws_vagrantfile
* Partially addresses #2855
Testing: i used these changes and my normal process to stand up a dev site, momentary.dev.buttonweavers.com.  Assuming CircleCI passes, if the site is accessible and works at all, the changes are okay, and should be merged.
=> Changes needed to launch a dev site instance in VPC

deploy/vagrant/manifests/init.pp, deploy/vagrant/modules/mysql/manifests/init.pp
* Partially addresses #2855 
* This PR is what's needed to create new instances via vagrant that use RDS databases --- it's a noop for instances that use local mysql
=> Changes need to run RDS dev site using new EIP

src/ui/about.html, src/ui/active_players.html, src/ui/buttons.html, src/ui/create_game.html, src/ui/create_user.html, src/ui/faq.html, src/ui/forgot_password.html, src/ui/forum.html, src/ui/game.html, src/ui/getting-started.html, src/ui/help.html, src/ui/history.html, src/ui/index.html, src/ui/js/Loader.js, src/ui/open_games.html, src/ui/prefs.html, src/ui/privacy.html, src/ui/profile.html, src/ui/skills.html, src/ui/verify.html, src/ui/verify_reset.html
* Fixes #2818 
* Dev site up at: https://temporary.dev.buttonweavers.com
=> Don't cache JS files at the AJAX level

src/ui/js/GettingStarted.js, src/ui/js/Help.js, test/src/ui/js/test_Faq.js, test/src/ui/js/test_GettingStarted.js
Fixes #2467.
This is a first draft, I'm happy to take input on the content.
@cgolubi1, could we have a test site for this so that testers can take a look at the new tutorial page, please?
To do:
=> Filled in tutorial page

LICENSE.txt, src/ui/js/Login.js, test/src/ui/js/test_Login.js
Apparently, we're almost at 2023. Got to be ready for it!
=> Yearly update of copyright year to 2023

src/ui/js/Faq.js, src/ui/js/Forum.js, src/ui/js/Login.js, test/src/ui/js/test_Login.js
=> Changed "Forum" to "Forums" in header text

.circleci/config.yml, deploy/vagrant/modules/buttonmen/manifests/init.pp, deploy/vagrant/modules/buttonmen/templates/branch_database_rebuild_test.erb
It's gotten a bit time-consuming and annoying to do this check by hand and verify that i've done it.
I believe this script will cause circleci to do the check for me, so people can see their own results.
=> Do an update-vs-rebuild database test within circleci

LICENSE.txt, src/ui/js/Login.js, test/src/ui/js/test_Login.js
Once a year, we get the joy of updating the copyright year because we ate'nt dead yet!
=> Yearly update of copyright year to 2024

deploy/docker/deploy_buttonmen_site
Discovered during staging smoke-testing on #2937
=> Fix deployment script typo impacting repos with hyphens in their names

deploy/docker/startup.sh, deploy/vagrant/modules/buttonmen/manifests/init.pp, deploy/vagrant/modules/buttonmen/templates/send_hello_world_email.erb
Partially addresses #2908 
I've left the dev site running; you should be able to use the e-mail which was sent to buttonmen-help to get the IP address to SSH to this dev site's container.
=> Send a hello world e-mail whenever a new non-sandbox site is started

deploy/docker/startup.sh
I created a dev site for this, and it looks good:
```
$ ls -l /var/log/apache2
lrwxrwxrwx 1 root root 89 May  5 20:10 /var/log/apache2 -> /mnt/efs/2908-retain-apache-logs.cgolubi1.dev.buttonweavers.com/apache_logs/ip-10-0-0-205
```
```
$ ls -lart /var/log/apache2/
total 68
-rw-r-----  1 root adm      0 May  5 19:52 other_vhosts_access.log
drwxr-xr-x 17 root root  6144 May  5 20:10 ..
drwxr-x---  2 root adm   6144 May  5 20:10 .
-rw-r-----  1 root adm   2372 May  5 20:15 error.log
-rw-r-----  1 root adm  51675 May  5 20:17 access.log
```
And the contents of the access and error logs look normal.
=> Mount /var/log/apache2 from EFS so http logs will be retained across container replacement

src/ui/js/Env.js, src/ui/js/Forum.js, src/ui/js/Help.js
=> Replace references to the old Buttonweavers wiki at Wikia/Fandom with references to the new buttonmen.wiki wiki.

notes/engine/List_of_die_hooks_and_skills.txt, src/engine/BMBtnSkillBruno.php, src/engine/BMBtnSkillPappy.php, src/engine/BMGame.php, src/engine/BMGameAction.php, test/src/api/responder04Test.php, test/src/api/responderTestFramework.php
Supersedes #2905, partly addresses #372.
I've taken the pull request from @craw-daddy and added action logging.
To do:
=> Pappy and Bruno (take 2)

deploy/docker/deploy_buttonmen_site, deploy/docker/get_buttonmen_site_ipaddr, deploy/docker/teardown_buttonmen_site
* Fixes #2969 
Testing done:
Successfully deployed the dev site using deploy_buttonmen_site, and accessed it at:
https://2969-mixedcase-branch.cgolubi1.dev.buttonweavers.com
Checked that i could get the IP address:
```
$ env AWS_PROFILE=bm_deploy /Users/chaos/games/buttonmen/miniconda3/bin/python ./deploy/docker/get_buttonmen_site_ipaddr
54.174.119.68
```
Successfully tore the site down using teardown_buttonmen_site
=> docker repo name needs to be lowercase even if git branch name isn't

tools/api-client/python/replaytest/replay_loop
* Partially addresses #2953 
This sets up basic argument parsing and help text, and also makes number of games, player button, and opponent button, independently configurable.
=> Clean up argument parsing for replay_loop

src/engine/BMDieOption.php, src/engine/BMInterfaceGame.php
* #2972
```
UPDATES=
SCRIPTS=
```
=> Push changes from master to staging on 2024-08-16

src/api/ApiResponder.php, src/engine/BMInterfaceGame.php
* #2985
```
UPDATES=
SCRIPTS=
```
=> Push changes from master to staging on 2024-09-06

src/api/ApiResponder.php, src/engine/BMInterfaceGame.php, test/src/api/responder04Test.php
* #2990
```
UPDATES=
SCRIPTS=
```
=> Push changes from master to staging on 2024-10-11

tools/api-client/python/lib/random_ai.py
I created this for use in reproducing the bug in #2989, and wanted to commit it.
It's not perfect, and it doesn't directly test any new cases since the fix for the outstanding issue should be pretty solid.  But it establishes a framework for expecting `submitTurn` to fail, and that's something i should be able to build on to do a lot more fuzz-testing of things that shouldn't work, so i'd like to get it in the codebase.
=> With small probability, try an invalid attack, and make sure it fails

src/api/ApiResponder.php, src/engine/BMInterfaceGame.php, test/src/api/responder04Test.php
This update brings these approved pulls to the production branch:
* #2990
```
UPDATES=
SCRIPTS=
```
Once this pull is merged, i will load the changes on www.buttonweavers.com as part of #700.
=> Push changes from staging to production on 2024-10-13

tools/api-client/python/lib/random_ai.py
Sorry for the bother - i was in too much of a hurry to merge #2992 and didn't test it for whether the games it created could be replayed.  Rookie mistake, and i even have a flag to `replay_loop` to support that testing, i was just in a hurry.
Anyway, this PR fixes that one so when `submitTurn` fails expectedly, PHP-based replay testing correctly expects that failure as well.  I've tested it using `replay_loop -l`, where i've played 1200 novel games, replayed them all, and also replayed 1200 games from the archive, and those all passed.
=> Support replay for failed submitTurn entries

tools/api-client/python/lib/random_ai.py
* sometimes choose Default attacks, using dice which have already been chosen as valid for some attack type
* occasionally choose Surrender attacks
* occasionally intentionally submit an invalid attacker/defender combo
* after any submitTurn call fails, check that the API-reported game state is unchanged
These are additions i've had in mind to make for awhile, and the relevant code was top-of-mind because of the "invalid pass" fix.  I've run about 2000 novel and replayed games, and nothing has turned up, so i think it's okay to put this up for PR.
=> Add some more test cases to RandomAI

src/engine/BMBtnSkillRandomBM.php, src/engine/BMBtnSkillRandomBMDuoskill.php, src/engine/BMBtnSkillRandomBMFixed.php, src/engine/BMBtnSkillRandomBMMixed.php, src/engine/BMBtnSkillRandomBMMonoskill.php, src/engine/BMBtnSkillRandomBMPentaskill.php, src/engine/BMBtnSkillRandomBMTetraskill.php, src/engine/BMBtnSkillRandomBMTriskill.php, test/src/api/responder03Test.php, test/src/api/responderTestFramework.php, test/src/engine/BMBtnSkillRandomBMDuoskillTest.php, test/src/engine/BMBtnSkillRandomBMMixedTest.php, test/src/engine/BMBtnSkillRandomBMMonoskillTest.php, test/src/engine/BMBtnSkillRandomBMPentaskillTest.php, test/src/engine/BMBtnSkillRandomBMTest.php, test/src/engine/BMBtnSkillRandomBMTetraskillTest.php, test/src/engine/BMBtnSkillRandomBMTriskillTest.php, tools/api-client/python/lib/random_ai.py
* Partially addresses #2067 
Replacement PR for #2800 which is now ready to test
Replay testing has been done using commit [47ae228](https://github.com/buttonmen-dev/buttonmen/pull/2844/commits/47ae228d2d1f419ee5fff3dea1d5a9dee3139d89), see comment below for details.
Dev site: https://2067-enable-mad-mood.cgolubi1.dev.buttonweavers.com/
=> Enable Mad and Mood skills in RandomBM

LICENSE.txt, src/ui/js/Login.js, test/src/ui/js/test_Login.js
Moving right along ... to 2025!
=> Updated copyright year to 2025

LICENSE.txt, src/ui/js/Login.js, test/src/ui/js/test_Login.js, tools/api-client/python/replaytest/replay_loop
* #3022
```
UPDATES=
SCRIPTS=
```
=> Push changes from master to staging on 2025-01-17

src/api/ApiSpec.php, src/engine/BMInterface.php, test/src/api/responder00Test.php, test/src/ui/js/test_Overview.js, test/tools/api-client/python/lib/test_bmapi.py, test/tools/api-client/python/lib/test_bmutils.py
* #3031
```
UPDATES=
SCRIPTS=
```
=> Push changes from master to staging on 2025-03-28

src/engine/BMInterfaceGame.php, test/src/api/responder01Test.php, test/src/api/responderTestFramework.php, test/src/ui/js/test_Game.js
* Fixes #3050 
dev site at: https://3050-default-chat-privacy.cgolubi1.dev.buttonweavers.com
=> Create new games with private chat instead of with public chat

src/engine/BMInterfaceNewuser.php, test/src/api/responder00Test.php
This is a temporary band-aid for #2915.
=> Updated advice if verification email never arrives
